// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface AddFeedbackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.AddFeedbackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 candidate_id = 1;</code>
   */
  long getCandidateId();

  /**
   * <code>optional int32 rating_score = 2;</code>
   */
  int getRatingScore();

  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 3;</code>
   */
  java.util.List<in.trujobs.proto.FeedbackReasonObject> 
      getFeedbackReasonObjectList();
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 3;</code>
   */
  in.trujobs.proto.FeedbackReasonObject getFeedbackReasonObject(int index);
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 3;</code>
   */
  int getFeedbackReasonObjectCount();
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 3;</code>
   */
  java.util.List<? extends in.trujobs.proto.FeedbackReasonObjectOrBuilder> 
      getFeedbackReasonObjectOrBuilderList();
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 3;</code>
   */
  in.trujobs.proto.FeedbackReasonObjectOrBuilder getFeedbackReasonObjectOrBuilder(
      int index);
}
