// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface CandidateInformationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.CandidateInformationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string candidateMobile = 1;</code>
   */
  java.lang.String getCandidateMobile();
  /**
   * <code>optional string candidateMobile = 1;</code>
   */
  com.google.protobuf.ByteString
      getCandidateMobileBytes();
}
