// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface CandidateSkillObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.CandidateSkillObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 skillId = 1;</code>
   */
  int getSkillId();

  /**
   * <code>optional bool answer = 2;</code>
   */
  boolean getAnswer();
}
