// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface CompanyObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.CompanyObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 companyId = 1;</code>
   */
  long getCompanyId();

  /**
   * <code>optional string companyName = 2;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>optional string companyName = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>optional string companyEmployeeCount = 3;</code>
   */
  java.lang.String getCompanyEmployeeCount();
  /**
   * <code>optional string companyEmployeeCount = 3;</code>
   */
  com.google.protobuf.ByteString
      getCompanyEmployeeCountBytes();

  /**
   * <code>optional string companyWebsite = 4;</code>
   */
  java.lang.String getCompanyWebsite();
  /**
   * <code>optional string companyWebsite = 4;</code>
   */
  com.google.protobuf.ByteString
      getCompanyWebsiteBytes();

  /**
   * <code>optional string companyDescription = 5;</code>
   */
  java.lang.String getCompanyDescription();
  /**
   * <code>optional string companyDescription = 5;</code>
   */
  com.google.protobuf.ByteString
      getCompanyDescriptionBytes();

  /**
   * <code>optional string companyAddress = 6;</code>
   */
  java.lang.String getCompanyAddress();
  /**
   * <code>optional string companyAddress = 6;</code>
   */
  com.google.protobuf.ByteString
      getCompanyAddressBytes();

  /**
   * <code>optional string companyLogo = 7;</code>
   */
  java.lang.String getCompanyLogo();
  /**
   * <code>optional string companyLogo = 7;</code>
   */
  com.google.protobuf.ByteString
      getCompanyLogoBytes();

  /**
   * <code>optional .in.trujobs.proto.CompanyTypeObject companyType = 9;</code>
   */
  boolean hasCompanyType();
  /**
   * <code>optional .in.trujobs.proto.CompanyTypeObject companyType = 9;</code>
   */
  in.trujobs.proto.CompanyTypeObject getCompanyType();
  /**
   * <code>optional .in.trujobs.proto.CompanyTypeObject companyType = 9;</code>
   */
  in.trujobs.proto.CompanyTypeObjectOrBuilder getCompanyTypeOrBuilder();

  /**
   * <code>optional .in.trujobs.proto.LocalityObject companyLocality = 10;</code>
   */
  boolean hasCompanyLocality();
  /**
   * <code>optional .in.trujobs.proto.LocalityObject companyLocality = 10;</code>
   */
  in.trujobs.proto.LocalityObject getCompanyLocality();
  /**
   * <code>optional .in.trujobs.proto.LocalityObject companyLocality = 10;</code>
   */
  in.trujobs.proto.LocalityObjectOrBuilder getCompanyLocalityOrBuilder();

  /**
   * <code>repeated .in.trujobs.proto.JobPostObject companyOtherJobs = 11;</code>
   */
  java.util.List<in.trujobs.proto.JobPostObject> 
      getCompanyOtherJobsList();
  /**
   * <code>repeated .in.trujobs.proto.JobPostObject companyOtherJobs = 11;</code>
   */
  in.trujobs.proto.JobPostObject getCompanyOtherJobs(int index);
  /**
   * <code>repeated .in.trujobs.proto.JobPostObject companyOtherJobs = 11;</code>
   */
  int getCompanyOtherJobsCount();
  /**
   * <code>repeated .in.trujobs.proto.JobPostObject companyOtherJobs = 11;</code>
   */
  java.util.List<? extends in.trujobs.proto.JobPostObjectOrBuilder> 
      getCompanyOtherJobsOrBuilderList();
  /**
   * <code>repeated .in.trujobs.proto.JobPostObject companyOtherJobs = 11;</code>
   */
  in.trujobs.proto.JobPostObjectOrBuilder getCompanyOtherJobsOrBuilder(
      int index);
}
