// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface DegreeObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.DegreeObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 degreeId = 1;</code>
   */
  long getDegreeId();

  /**
   * <code>optional string degreeName = 2;</code>
   */
  java.lang.String getDegreeName();
  /**
   * <code>optional string degreeName = 2;</code>
   */
  com.google.protobuf.ByteString
      getDegreeNameBytes();
}
