// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface FeedbackReasonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.FeedbackReasonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 1;</code>
   */
  java.util.List<in.trujobs.proto.FeedbackReasonObject> 
      getFeedbackReasonObjectList();
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 1;</code>
   */
  in.trujobs.proto.FeedbackReasonObject getFeedbackReasonObject(int index);
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 1;</code>
   */
  int getFeedbackReasonObjectCount();
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 1;</code>
   */
  java.util.List<? extends in.trujobs.proto.FeedbackReasonObjectOrBuilder> 
      getFeedbackReasonObjectOrBuilderList();
  /**
   * <code>repeated .in.trujobs.proto.FeedbackReasonObject feedbackReasonObject = 1;</code>
   */
  in.trujobs.proto.FeedbackReasonObjectOrBuilder getFeedbackReasonObjectOrBuilder(
      int index);
}
