// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface FetchCandidateAlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.FetchCandidateAlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .in.trujobs.proto.FetchCandidateAlertResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .in.trujobs.proto.FetchCandidateAlertResponse.Status status = 1;</code>
   */
  in.trujobs.proto.FetchCandidateAlertResponse.Status getStatus();

  /**
   * <code>optional .in.trujobs.proto.FetchCandidateAlertResponse.Type alertType = 2;</code>
   */
  int getAlertTypeValue();
  /**
   * <code>optional .in.trujobs.proto.FetchCandidateAlertResponse.Type alertType = 2;</code>
   */
  in.trujobs.proto.FetchCandidateAlertResponse.Type getAlertType();

  /**
   * <code>optional string statusMessage = 3;</code>
   */
  java.lang.String getStatusMessage();
  /**
   * <code>optional string statusMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
