// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public final class Gen {
  private Gen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_TestMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_TestMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LogInRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LogInRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LogInResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LogInResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_SignUpRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_SignUpRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_SignUpResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_SignUpResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ResetPasswordRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ResetPasswordRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ResetPasswordResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ResetPasswordResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobRoleResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobRoleResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobRoleObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobRoleObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobPostResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobPostResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobPostObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobPostObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobPostDetailRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobPostDetailRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LocalityObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LocalityObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ExperienceObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ExperienceObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_EducationObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_EducationObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_TimeShiftObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_TimeShiftObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ApplyJobRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ApplyJobRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ApplyJobResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ApplyJobResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_AddJobRoleRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_AddJobRoleRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_AddJobRoleResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_AddJobRoleResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateInformationRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateInformationRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetCandidateInformationResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetCandidateInformationResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetJobPostDetailsRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetJobPostDetailsRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetJobPostDetailsResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetJobPostDetailsResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CompanyObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CompanyObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CompanyTypeObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CompanyTypeObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_HomeLocalityRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_HomeLocalityResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_HomeLocalityResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobFilterRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobFilterRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_FetchCandidateAlertRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_FetchCandidateAlertRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_FetchCandidateAlertResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_FetchCandidateAlertResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobSearchRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobSearchRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobSearchByJobRoleRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobSearchByJobRoleRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tgen.proto\022\020in.trujobs.proto\"1\n\013TestMes" +
      "sage\022\020\n\010testName\030\001 \001(\t\022\020\n\010testPage\030\002 \001(\t" +
      "\"B\n\014LogInRequest\022\027\n\017candidateMobile\030\001 \001(" +
      "\t\022\031\n\021candidatePassword\030\002 \001(\t\"\366\003\n\rLogInRe" +
      "sponse\0226\n\006status\030\001 \001(\0162&.in.trujobs.prot" +
      "o.LogInResponse.Status\022\016\n\006leadId\030\002 \001(\003\022\023" +
      "\n\013candidateId\030\003 \001(\003\022\027\n\017candidateGender\030\004" +
      " \001(\005\022\032\n\022candidateFirstName\030\005 \001(\t\022\031\n\021cand" +
      "idateLastName\030\006 \001(\t\022\033\n\023candidateIsAssess" +
      "ed\030\007 \001(\005\022\022\n\nsession_id\030\010 \001(\t\022\035\n\025session_",
      "expiry_millis\030\t \001(\003\022\022\n\nminProfile\030\n \001(\005\022" +
      "\036\n\026candidateJobPrefStatus\030\013 \001(\005\022#\n\033candi" +
      "dateHomeLocalityStatus\030\014 \001(\005\022\035\n\025candidat" +
      "eHomeLatitude\030\r \001(\001\022\036\n\026candidateHomeLong" +
      "itude\030\016 \001(\001\"P\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SU" +
      "CCESS\020\001\022\013\n\007FAILURE\020\002\022\013\n\007NO_USER\020\003\022\022\n\016WRO" +
      "NG_PASSWORD\020\004\"-\n\rSignUpRequest\022\014\n\004name\030\001" +
      " \001(\t\022\016\n\006mobile\030\002 \001(\t\"\224\001\n\016SignUpResponse\022" +
      "7\n\006status\030\001 \001(\0162\'.in.trujobs.proto.SignU" +
      "pResponse.Status\022\024\n\014generatedOtp\030\002 \001(\005\"3",
      "\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\017\n\013US" +
      "ER_EXISTS\020\003\"8\n\024ResetPasswordRequest\022\016\n\006m" +
      "obile\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\246\001\n\025ResetP" +
      "asswordResponse\022>\n\006status\030\001 \001(\0162..in.tru" +
      "jobs.proto.ResetPasswordResponse.Status\022" +
      "\013\n\003otp\030\002 \001(\005\"@\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007S" +
      "UCCESS\020\001\022\013\n\007FAILURE\020\002\022\017\n\013USER_EXISTS\020\003\"C" +
      "\n\017JobRoleResponse\0220\n\007jobRole\030\001 \003(\0132\037.in." +
      "trujobs.proto.JobRoleObject\"L\n\rJobRoleOb" +
      "ject\022\021\n\tjobRoleId\030\001 \001(\003\022\023\n\013jobRoleName\030\002",
      " \001(\t\022\023\n\013jobRoleIcon\030\003 \001(\t\"C\n\017JobPostResp" +
      "onse\0220\n\007jobPost\030\001 \003(\0132\037.in.trujobs.proto" +
      ".JobPostObject\"\313\005\n\rJobPostObject\022\021\n\tjobP" +
      "ostId\030\001 \001(\003\022\024\n\014jobPostTitle\030\002 \001(\t\022\032\n\022job" +
      "PostCompanyName\030\003 \001(\t\022\030\n\020jobPostMinSalar" +
      "y\030\004 \001(\003\022\030\n\020jobPostMaxSalary\030\005 \001(\003\0229\n\017job" +
      "PostLocality\030\006 \003(\0132 .in.trujobs.proto.Lo" +
      "calityObject\022\032\n\022jobPostCompanyLogo\030\007 \001(\t" +
      "\022=\n\021jobPostExperience\030\010 \001(\0132\".in.trujobs" +
      ".proto.ExperienceObject\0227\n\014jobPostShift\030",
      "\t \001(\0132!.in.trujobs.proto.TimeShiftObject" +
      "\022\021\n\tvacancies\030\n \001(\005\022\032\n\022jobPostDescriptio" +
      "n\030\013 \001(\t\022\031\n\021jobPostIncentives\030\014 \001(\t\022\036\n\026jo" +
      "bPostMinRequirements\030\r \001(\t\022\026\n\016jobPostAdd" +
      "ress\030\016 \001(\t\022\033\n\023jobPostWorkFromHome\030\017 \001(\005\022" +
      "\032\n\022jobPostWorkingDays\030\020 \001(\t\0224\n\teducation" +
      "\030\021 \001(\0132!.in.trujobs.proto.EducationObjec" +
      "t\0220\n\007jobRole\030\022 \001(\0132\037.in.trujobs.proto.Jo" +
      "bRoleObject\022\035\n\025jobPostCreationMillis\030\023 \001" +
      "(\003\022\030\n\020jobPostStartTime\030\024 \001(\005\022\026\n\016jobPostE",
      "ndTime\030\025 \001(\005\")\n\024JobPostDetailRequest\022\021\n\t" +
      "jobPostId\030\001 \001(\003\":\n\016LocalityObject\022\022\n\nloc" +
      "alityId\030\001 \001(\003\022\024\n\014localityName\030\002 \001(\t\"@\n\020E" +
      "xperienceObject\022\024\n\014experienceId\030\001 \001(\003\022\026\n" +
      "\016experienceType\030\002 \001(\t\"=\n\017EducationObject" +
      "\022\023\n\013educationId\030\001 \001(\003\022\025\n\reducationName\030\002" +
      " \001(\t\"=\n\017TimeShiftObject\022\023\n\013timeShiftId\030\001" +
      " \001(\003\022\025\n\rtimeShiftName\030\002 \001(\t\"Q\n\017ApplyJobR" +
      "equest\022\027\n\017candidateMobile\030\001 \001(\t\022\021\n\tjobPo" +
      "stId\030\002 \001(\003\022\022\n\nlocalityId\030\003 \001(\003\"\261\001\n\020Apply",
      "JobResponse\0229\n\006status\030\001 \001(\0162).in.trujobs" +
      ".proto.ApplyJobResponse.Status\"b\n\006Status" +
      "\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\022" +
      "\023\n\017ALREADY_APPLIED\020\003\022\020\n\014NO_CANDIDATE\020\004\022\n" +
      "\n\006NO_JOB\020\005\"|\n\021AddJobRoleRequest\022\027\n\017candi" +
      "dateMobile\030\001 \001(\t\022\030\n\020jobRolePrefOneId\030\002 \001" +
      "(\003\022\030\n\020jobRolePrefTwoId\030\003 \001(\003\022\032\n\022jobRoleP" +
      "refThreeId\030\004 \001(\003\"\202\001\n\022AddJobRoleResponse\022" +
      ";\n\006status\030\001 \001(\0162+.in.trujobs.proto.AddJo" +
      "bRoleResponse.Status\"/\n\006Status\022\013\n\007UNKNOW",
      "N\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\"6\n\033Candida" +
      "teInformationRequest\022\027\n\017candidateMobile\030" +
      "\001 \001(\t\"\322\001\n\037GetCandidateInformationRespons" +
      "e\022H\n\006status\030\001 \001(\01628.in.trujobs.proto.Get" +
      "CandidateInformationResponse.Status\0224\n\tc" +
      "andidate\030\002 \001(\0132!.in.trujobs.proto.Candid" +
      "ateObject\"/\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCC" +
      "ESS\020\001\022\013\n\007FAILURE\020\002\"\215\004\n\017CandidateObject\022\023" +
      "\n\013candidateId\030\001 \001(\003\022\032\n\022candidateFirstNam" +
      "e\030\002 \001(\t\022\031\n\021candidateLastName\030\003 \001(\t\022\033\n\023ca",
      "ndidateIsAssessed\030\004 \001(\005\022#\n\033candidateMinP" +
      "rofileComplete\030\005 \001(\005\022\027\n\017candidateGender\030" +
      "\006 \001(\005\022\027\n\017candidateMobile\030\007 \001(\t\022\024\n\014candid" +
      "ateAge\030\010 \001(\005\022?\n\025candidateHomelocality\030\t " +
      "\001(\0132 .in.trujobs.proto.LocalityObject\022?\n" +
      "\025candidateLocationPref\030\n \003(\0132 .in.trujob" +
      "s.proto.LocalityObject\022=\n\024candidateJobRo" +
      "lePref\030\013 \003(\0132\037.in.trujobs.proto.JobRoleO" +
      "bject\022A\n\026candidateTimeShiftPref\030\014 \001(\0132!." +
      "in.trujobs.proto.TimeShiftObject\022 \n\030cand",
      "idateTotalExperience\030\r \001(\005\"-\n\030GetJobPost" +
      "DetailsRequest\022\021\n\tjobPostId\030\001 \001(\003\"\363\001\n\031Ge" +
      "tJobPostDetailsResponse\022B\n\006status\030\001 \001(\0162" +
      "2.in.trujobs.proto.GetJobPostDetailsResp" +
      "onse.Status\0220\n\007jobPost\030\002 \001(\0132\037.in.trujob" +
      "s.proto.JobPostObject\0220\n\007company\030\003 \001(\0132\037" +
      ".in.trujobs.proto.CompanyObject\".\n\006Statu" +
      "s\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\n\n\006NO_JOB\020\002\"" +
      "\346\002\n\rCompanyObject\022\021\n\tcompanyId\030\001 \001(\003\022\023\n\013" +
      "companyName\030\002 \001(\t\022\034\n\024companyEmployeeCoun",
      "t\030\003 \001(\t\022\026\n\016companyWebsite\030\004 \001(\t\022\032\n\022compa" +
      "nyDescription\030\005 \001(\t\022\026\n\016companyAddress\030\006 " +
      "\001(\t\022\023\n\013companyLogo\030\007 \001(\t\0228\n\013companyType\030" +
      "\t \001(\0132#.in.trujobs.proto.CompanyTypeObje" +
      "ct\0229\n\017companyLocality\030\n \001(\0132 .in.trujobs" +
      ".proto.LocalityObject\0229\n\020companyOtherJob" +
      "s\030\013 \003(\0132\037.in.trujobs.proto.JobPostObject" +
      "\"C\n\021CompanyTypeObject\022\025\n\rcompanyTypeId\030\001" +
      " \001(\003\022\027\n\017companyTypeName\030\002 \001(\t\"~\n\023HomeLoc" +
      "alityRequest\022\013\n\003lat\030\001 \001(\001\022\013\n\003lng\030\002 \001(\001\022\014",
      "\n\004name\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\022\030\n\020candida" +
      "te_mobile\030\005 \001(\t\022\024\n\014candidate_id\030\006 \001(\003\"\232\001" +
      "\n\024HomeLocalityResponse\022=\n\006status\030\001 \001(\0162-" +
      ".in.trujobs.proto.HomeLocalityResponse.S" +
      "tatus\"C\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020" +
      "\001\022\013\n\007FAILURE\020\002\022\022\n\016USER_NOT_FOUND\020\003\"\312\005\n\020J" +
      "obFilterRequest\0229\n\006salary\030\001 \001(\0162).in.tru" +
      "jobs.proto.JobFilterRequest.Salary\022:\n\003ex" +
      "p\030\002 \001(\0162-.in.trujobs.proto.JobFilterRequ" +
      "est.Experience\0229\n\003edu\030\003 \001(\0162,.in.trujobs",
      ".proto.JobFilterRequest.Education\0229\n\006gen" +
      "der\030\004 \001(\0162).in.trujobs.proto.JobFilterRe" +
      "quest.Gender\022\033\n\023sort_by_date_posted\030\005 \001(" +
      "\010\022\026\n\016sort_by_salary\030\006 \001(\010\022\030\n\020candidate_m" +
      "obile\030\007 \001(\t\022\033\n\023job_search_latitude\030\010 \001(\001" +
      "\022\034\n\024job_search_longitude\030\t \001(\001\"t\n\006Salary" +
      "\022\016\n\nANY_SALARY\020\000\022\020\n\014EIGHT_K_PLUS\020\001\022\016\n\nTE" +
      "N_K_PLUS\020\002\022\021\n\rTWELVE_K_PLUS\020\003\022\022\n\016FIFTEEN" +
      "_K_PLUS\020\004\022\021\n\rTWENTY_K_PLUS\020\005\">\n\nExperien" +
      "ce\022\022\n\016ANY_EXPERIENCE\020\000\022\013\n\007FRESHER\020\001\022\017\n\013E",
      "XPERIENCED\020\002\"Y\n\tEducation\022\021\n\rANY_EDUCATI" +
      "ON\020\000\022\n\n\006LT_TEN\020\001\022\014\n\010TEN_PASS\020\002\022\017\n\013TWELVE" +
      "_PASS\020\003\022\006\n\002UG\020\004\022\006\n\002PG\020\005\".\n\006Gender\022\016\n\nANY" +
      "_GENDER\020\000\022\010\n\004MALE\020\001\022\n\n\006FEMALE\020\002\"6\n\032Fetch" +
      "CandidateAlertRequest\022\030\n\020candidate_mobil" +
      "e\030\001 \001(\t\"\353\002\n\033FetchCandidateAlertResponse\022" +
      "D\n\006status\030\001 \001(\01624.in.trujobs.proto.Fetch" +
      "CandidateAlertResponse.Status\022E\n\talertTy" +
      "pe\030\002 \001(\01622.in.trujobs.proto.FetchCandida" +
      "teAlertResponse.Type\022\024\n\014alertMessage\030\003 \001",
      "(\t\"\"\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\"\204" +
      "\001\n\004Type\022\024\n\020COMPLETE_PROFILE\020\000\022\027\n\023INTERVI" +
      "EW_SCHEDULED\020\001\022\032\n\026JOINING_DATE_CONFIRMED" +
      "\020\002\022\027\n\023PROFILE_DEACTIVATED\020\003\022\030\n\024NEW_JOBS_" +
      "IN_LOCALITY\020\004\"\337\001\n\020JobSearchRequest\022\020\n\010la" +
      "titude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\030\n\020candi" +
      "date_mobile\030\003 \001(\t\022<\n\020jobFilterRequest\030\004 " +
      "\001(\0132\".in.trujobs.proto.JobFilterRequest\022" +
      "N\n\031jobSearchByJobRoleRequest\030\005 \001(\0132+.in." +
      "trujobs.proto.JobSearchByJobRoleRequest\"",
      "_\n\031JobSearchByJobRoleRequest\022\024\n\014jobRoleI" +
      "dOne\030\001 \001(\003\022\024\n\014jobRoleIdTwo\030\002 \001(\003\022\026\n\016JobR" +
      "oleIdThree\030\003 \001(\003B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_in_trujobs_proto_TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_in_trujobs_proto_TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_TestMessage_descriptor,
        new java.lang.String[] { "TestName", "TestPage", });
    internal_static_in_trujobs_proto_LogInRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_in_trujobs_proto_LogInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LogInRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "CandidatePassword", });
    internal_static_in_trujobs_proto_LogInResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_in_trujobs_proto_LogInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LogInResponse_descriptor,
        new java.lang.String[] { "Status", "LeadId", "CandidateId", "CandidateGender", "CandidateFirstName", "CandidateLastName", "CandidateIsAssessed", "SessionId", "SessionExpiryMillis", "MinProfile", "CandidateJobPrefStatus", "CandidateHomeLocalityStatus", "CandidateHomeLatitude", "CandidateHomeLongitude", });
    internal_static_in_trujobs_proto_SignUpRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_in_trujobs_proto_SignUpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_SignUpRequest_descriptor,
        new java.lang.String[] { "Name", "Mobile", });
    internal_static_in_trujobs_proto_SignUpResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_in_trujobs_proto_SignUpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_SignUpResponse_descriptor,
        new java.lang.String[] { "Status", "GeneratedOtp", });
    internal_static_in_trujobs_proto_ResetPasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_in_trujobs_proto_ResetPasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ResetPasswordRequest_descriptor,
        new java.lang.String[] { "Mobile", "Password", });
    internal_static_in_trujobs_proto_ResetPasswordResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_in_trujobs_proto_ResetPasswordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ResetPasswordResponse_descriptor,
        new java.lang.String[] { "Status", "Otp", });
    internal_static_in_trujobs_proto_JobRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_in_trujobs_proto_JobRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobRoleResponse_descriptor,
        new java.lang.String[] { "JobRole", });
    internal_static_in_trujobs_proto_JobRoleObject_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_in_trujobs_proto_JobRoleObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobRoleObject_descriptor,
        new java.lang.String[] { "JobRoleId", "JobRoleName", "JobRoleIcon", });
    internal_static_in_trujobs_proto_JobPostResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_in_trujobs_proto_JobPostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobPostResponse_descriptor,
        new java.lang.String[] { "JobPost", });
    internal_static_in_trujobs_proto_JobPostObject_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_in_trujobs_proto_JobPostObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobPostObject_descriptor,
        new java.lang.String[] { "JobPostId", "JobPostTitle", "JobPostCompanyName", "JobPostMinSalary", "JobPostMaxSalary", "JobPostLocality", "JobPostCompanyLogo", "JobPostExperience", "JobPostShift", "Vacancies", "JobPostDescription", "JobPostIncentives", "JobPostMinRequirements", "JobPostAddress", "JobPostWorkFromHome", "JobPostWorkingDays", "Education", "JobRole", "JobPostCreationMillis", "JobPostStartTime", "JobPostEndTime", });
    internal_static_in_trujobs_proto_JobPostDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_in_trujobs_proto_JobPostDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobPostDetailRequest_descriptor,
        new java.lang.String[] { "JobPostId", });
    internal_static_in_trujobs_proto_LocalityObject_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_in_trujobs_proto_LocalityObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LocalityObject_descriptor,
        new java.lang.String[] { "LocalityId", "LocalityName", });
    internal_static_in_trujobs_proto_ExperienceObject_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_in_trujobs_proto_ExperienceObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ExperienceObject_descriptor,
        new java.lang.String[] { "ExperienceId", "ExperienceType", });
    internal_static_in_trujobs_proto_EducationObject_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_in_trujobs_proto_EducationObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_EducationObject_descriptor,
        new java.lang.String[] { "EducationId", "EducationName", });
    internal_static_in_trujobs_proto_TimeShiftObject_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_in_trujobs_proto_TimeShiftObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_TimeShiftObject_descriptor,
        new java.lang.String[] { "TimeShiftId", "TimeShiftName", });
    internal_static_in_trujobs_proto_ApplyJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_in_trujobs_proto_ApplyJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ApplyJobRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "JobPostId", "LocalityId", });
    internal_static_in_trujobs_proto_ApplyJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_in_trujobs_proto_ApplyJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ApplyJobResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_AddJobRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_in_trujobs_proto_AddJobRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_AddJobRoleRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "JobRolePrefOneId", "JobRolePrefTwoId", "JobRolePrefThreeId", });
    internal_static_in_trujobs_proto_AddJobRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_in_trujobs_proto_AddJobRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_AddJobRoleResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_CandidateInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_in_trujobs_proto_CandidateInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateInformationRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", });
    internal_static_in_trujobs_proto_GetCandidateInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_in_trujobs_proto_GetCandidateInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetCandidateInformationResponse_descriptor,
        new java.lang.String[] { "Status", "Candidate", });
    internal_static_in_trujobs_proto_CandidateObject_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_in_trujobs_proto_CandidateObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateObject_descriptor,
        new java.lang.String[] { "CandidateId", "CandidateFirstName", "CandidateLastName", "CandidateIsAssessed", "CandidateMinProfileComplete", "CandidateGender", "CandidateMobile", "CandidateAge", "CandidateHomelocality", "CandidateLocationPref", "CandidateJobRolePref", "CandidateTimeShiftPref", "CandidateTotalExperience", });
    internal_static_in_trujobs_proto_GetJobPostDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_in_trujobs_proto_GetJobPostDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetJobPostDetailsRequest_descriptor,
        new java.lang.String[] { "JobPostId", });
    internal_static_in_trujobs_proto_GetJobPostDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_in_trujobs_proto_GetJobPostDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetJobPostDetailsResponse_descriptor,
        new java.lang.String[] { "Status", "JobPost", "Company", });
    internal_static_in_trujobs_proto_CompanyObject_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_in_trujobs_proto_CompanyObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CompanyObject_descriptor,
        new java.lang.String[] { "CompanyId", "CompanyName", "CompanyEmployeeCount", "CompanyWebsite", "CompanyDescription", "CompanyAddress", "CompanyLogo", "CompanyType", "CompanyLocality", "CompanyOtherJobs", });
    internal_static_in_trujobs_proto_CompanyTypeObject_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_in_trujobs_proto_CompanyTypeObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CompanyTypeObject_descriptor,
        new java.lang.String[] { "CompanyTypeId", "CompanyTypeName", });
    internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_in_trujobs_proto_HomeLocalityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor,
        new java.lang.String[] { "Lat", "Lng", "Name", "Address", "CandidateMobile", "CandidateId", });
    internal_static_in_trujobs_proto_HomeLocalityResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_in_trujobs_proto_HomeLocalityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_HomeLocalityResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_JobFilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_in_trujobs_proto_JobFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobFilterRequest_descriptor,
        new java.lang.String[] { "Salary", "Exp", "Edu", "Gender", "SortByDatePosted", "SortBySalary", "CandidateMobile", "JobSearchLatitude", "JobSearchLongitude", });
    internal_static_in_trujobs_proto_FetchCandidateAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_in_trujobs_proto_FetchCandidateAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_FetchCandidateAlertRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", });
    internal_static_in_trujobs_proto_FetchCandidateAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_in_trujobs_proto_FetchCandidateAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_FetchCandidateAlertResponse_descriptor,
        new java.lang.String[] { "Status", "AlertType", "AlertMessage", });
    internal_static_in_trujobs_proto_JobSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_in_trujobs_proto_JobSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobSearchRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "CandidateMobile", "JobFilterRequest", "JobSearchByJobRoleRequest", });
    internal_static_in_trujobs_proto_JobSearchByJobRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_in_trujobs_proto_JobSearchByJobRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobSearchByJobRoleRequest_descriptor,
        new java.lang.String[] { "JobRoleIdOne", "JobRoleIdTwo", "JobRoleIdThree", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
