// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public final class Gen {
  private Gen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_TestMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_TestMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LogInRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LogInRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LogInResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LogInResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_SignUpRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_SignUpRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_SignUpResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_SignUpResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ResetPasswordRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ResetPasswordRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ResetPasswordResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ResetPasswordResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobRoleResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobRoleResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobRoleObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobRoleObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobPostResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobPostResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobPostObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobPostObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobPostDetailRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobPostDetailRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LocalityObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LocalityObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ExperienceObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ExperienceObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_EducationObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_EducationObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_TimeShiftObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_TimeShiftObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ApplyJobRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ApplyJobRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_ApplyJobResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_ApplyJobResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_AddJobRoleRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_AddJobRoleRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_AddJobRoleResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_AddJobRoleResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateInformationRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateInformationRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetCandidateInformationResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetCandidateInformationResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetJobPostDetailsRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetJobPostDetailsRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetJobPostDetailsResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetJobPostDetailsResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CompanyObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CompanyObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CompanyTypeObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CompanyTypeObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_HomeLocalityRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_HomeLocalityResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_HomeLocalityResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateEducationObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateEducationObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_DegreeObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_DegreeObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateAppliedJobsRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateAppliedJobsRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateAppliedJobsResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateAppliedJobsResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_JobApplicationObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_JobApplicationObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_UpdateCandidateBasicProfileRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_UpdateCandidateBasicProfileRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_UpdateCandidateExperienceProfileRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_UpdateCandidateExperienceProfileRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_UpdateCandidateEducationProfileRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_UpdateCandidateEducationProfileRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_UpdateCandidateBasicProfileResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_UpdateCandidateBasicProfileResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetCandidateBasicProfileStaticResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetCandidateBasicProfileStaticResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetCandidateExperienceProfileStaticResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetCandidateExperienceProfileStaticResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_GetCandidateEducationProfileStaticResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_GetCandidateEducationProfileStaticResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LanguageObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LanguageObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_SkillObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_SkillObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_LanguageKnownObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_LanguageKnownObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_in_trujobs_proto_CandidateSkillObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_in_trujobs_proto_CandidateSkillObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tgen.proto\022\020in.trujobs.proto\"1\n\013TestMes" +
      "sage\022\020\n\010testName\030\001 \001(\t\022\020\n\010testPage\030\002 \001(\t" +
      "\"B\n\014LogInRequest\022\027\n\017candidateMobile\030\001 \001(" +
      "\t\022\031\n\021candidatePassword\030\002 \001(\t\"\267\003\n\rLogInRe" +
      "sponse\0226\n\006status\030\001 \001(\0162&.in.trujobs.prot" +
      "o.LogInResponse.Status\022\016\n\006leadId\030\002 \001(\003\022\023" +
      "\n\013candidateId\030\003 \001(\003\022\027\n\017candidateGender\030\004" +
      " \001(\005\022\032\n\022candidateFirstName\030\005 \001(\t\022\031\n\021cand" +
      "idateLastName\030\006 \001(\t\022\033\n\023candidateIsAssess" +
      "ed\030\007 \001(\005\022\022\n\nsession_id\030\010 \001(\t\022\035\n\025session_",
      "expiry_millis\030\t \001(\003\022\022\n\nminProfile\030\n \001(\005\022" +
      "\036\n\026candidateJobPrefStatus\030\013 \001(\005\022#\n\033candi" +
      "dateHomeLocalityStatus\030\014 \001(\005\"P\n\006Status\022\013" +
      "\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\022\013\n" +
      "\007NO_USER\020\003\022\022\n\016WRONG_PASSWORD\020\004\"-\n\rSignUp" +
      "Request\022\014\n\004name\030\001 \001(\t\022\016\n\006mobile\030\002 \001(\t\"\224\001" +
      "\n\016SignUpResponse\0227\n\006status\030\001 \001(\0162\'.in.tr" +
      "ujobs.proto.SignUpResponse.Status\022\024\n\014gen" +
      "eratedOtp\030\002 \001(\005\"3\n\006Status\022\013\n\007UNKNOWN\020\000\022\013" +
      "\n\007SUCCESS\020\001\022\017\n\013USER_EXISTS\020\003\"8\n\024ResetPas",
      "swordRequest\022\016\n\006mobile\030\001 \001(\t\022\020\n\010password" +
      "\030\002 \001(\t\"\246\001\n\025ResetPasswordResponse\022>\n\006stat" +
      "us\030\001 \001(\0162..in.trujobs.proto.ResetPasswor" +
      "dResponse.Status\022\013\n\003otp\030\002 \001(\005\"@\n\006Status\022" +
      "\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\022\017" +
      "\n\013USER_EXISTS\020\003\"C\n\017JobRoleResponse\0220\n\007jo" +
      "bRole\030\001 \003(\0132\037.in.trujobs.proto.JobRoleOb" +
      "ject\"L\n\rJobRoleObject\022\021\n\tjobRoleId\030\001 \001(\003" +
      "\022\023\n\013jobRoleName\030\002 \001(\t\022\023\n\013jobRoleIcon\030\003 \001" +
      "(\t\"C\n\017JobPostResponse\0220\n\007jobPost\030\001 \003(\0132\037",
      ".in.trujobs.proto.JobPostObject\"\313\005\n\rJobP" +
      "ostObject\022\021\n\tjobPostId\030\001 \001(\003\022\024\n\014jobPostT" +
      "itle\030\002 \001(\t\022\032\n\022jobPostCompanyName\030\003 \001(\t\022\030" +
      "\n\020jobPostMinSalary\030\004 \001(\003\022\030\n\020jobPostMaxSa" +
      "lary\030\005 \001(\003\0229\n\017jobPostLocality\030\006 \003(\0132 .in" +
      ".trujobs.proto.LocalityObject\022\032\n\022jobPost" +
      "CompanyLogo\030\007 \001(\t\022=\n\021jobPostExperience\030\010" +
      " \001(\0132\".in.trujobs.proto.ExperienceObject" +
      "\0227\n\014jobPostShift\030\t \001(\0132!.in.trujobs.prot" +
      "o.TimeShiftObject\022\021\n\tvacancies\030\n \001(\005\022\032\n\022",
      "jobPostDescription\030\013 \001(\t\022\031\n\021jobPostIncen" +
      "tives\030\014 \001(\t\022\036\n\026jobPostMinRequirements\030\r " +
      "\001(\t\022\026\n\016jobPostAddress\030\016 \001(\t\022\033\n\023jobPostWo" +
      "rkFromHome\030\017 \001(\005\022\032\n\022jobPostWorkingDays\030\020" +
      " \001(\t\0224\n\teducation\030\021 \001(\0132!.in.trujobs.pro" +
      "to.EducationObject\0220\n\007jobRole\030\022 \001(\0132\037.in" +
      ".trujobs.proto.JobRoleObject\022\035\n\025jobPostC" +
      "reationMillis\030\023 \001(\003\022\030\n\020jobPostStartTime\030" +
      "\024 \001(\005\022\026\n\016jobPostEndTime\030\025 \001(\005\")\n\024JobPost" +
      "DetailRequest\022\021\n\tjobPostId\030\001 \001(\003\":\n\016Loca",
      "lityObject\022\022\n\nlocalityId\030\001 \001(\003\022\024\n\014locali" +
      "tyName\030\002 \001(\t\"@\n\020ExperienceObject\022\024\n\014expe" +
      "rienceId\030\001 \001(\003\022\026\n\016experienceType\030\002 \001(\t\"=" +
      "\n\017EducationObject\022\023\n\013educationId\030\001 \001(\003\022\025" +
      "\n\reducationName\030\002 \001(\t\"=\n\017TimeShiftObject" +
      "\022\023\n\013timeShiftId\030\001 \001(\003\022\025\n\rtimeShiftName\030\002" +
      " \001(\t\"Q\n\017ApplyJobRequest\022\027\n\017candidateMobi" +
      "le\030\001 \001(\t\022\021\n\tjobPostId\030\002 \001(\003\022\022\n\nlocalityI" +
      "d\030\003 \001(\003\"\261\001\n\020ApplyJobResponse\0229\n\006status\030\001" +
      " \001(\0162).in.trujobs.proto.ApplyJobResponse",
      ".Status\"b\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCES" +
      "S\020\001\022\013\n\007FAILURE\020\002\022\023\n\017ALREADY_APPLIED\020\003\022\020\n" +
      "\014NO_CANDIDATE\020\004\022\n\n\006NO_JOB\020\005\"|\n\021AddJobRol" +
      "eRequest\022\027\n\017candidateMobile\030\001 \001(\t\022\030\n\020job" +
      "RolePrefOneId\030\002 \001(\003\022\030\n\020jobRolePrefTwoId\030" +
      "\003 \001(\003\022\032\n\022jobRolePrefThreeId\030\004 \001(\003\"\202\001\n\022Ad" +
      "dJobRoleResponse\022;\n\006status\030\001 \001(\0162+.in.tr" +
      "ujobs.proto.AddJobRoleResponse.Status\"/\n" +
      "\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAI" +
      "LURE\020\002\"6\n\033CandidateInformationRequest\022\027\n",
      "\017candidateMobile\030\001 \001(\t\"\205\002\n\037GetCandidateI" +
      "nformationResponse\022H\n\006status\030\001 \001(\01628.in." +
      "trujobs.proto.GetCandidateInformationRes" +
      "ponse.Status\0224\n\tcandidate\030\002 \001(\0132!.in.tru" +
      "jobs.proto.CandidateObject\0221\n\010jobRoles\030\003" +
      " \003(\0132\037.in.trujobs.proto.JobRoleObject\"/\n" +
      "\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAI" +
      "LURE\020\002\"\241\007\n\017CandidateObject\022\023\n\013candidateI" +
      "d\030\001 \001(\003\022\032\n\022candidateFirstName\030\002 \001(\t\022\031\n\021c" +
      "andidateLastName\030\003 \001(\t\022\033\n\023candidateIsAss",
      "essed\030\004 \001(\005\022#\n\033candidateMinProfileComple" +
      "te\030\005 \001(\005\022\027\n\017candidateGender\030\006 \001(\005\022\027\n\017can" +
      "didateMobile\030\007 \001(\t\022\024\n\014candidateAge\030\010 \001(\005" +
      "\022$\n\034candidateLastWithdrawnSalary\030\t \001(\003\022?" +
      "\n\025candidateHomelocality\030\n \001(\0132 .in.trujo" +
      "bs.proto.LocalityObject\022?\n\025candidateLoca" +
      "tionPref\030\013 \003(\0132 .in.trujobs.proto.Locali" +
      "tyObject\022=\n\024candidateJobRolePref\030\014 \003(\0132\037" +
      ".in.trujobs.proto.JobRoleObject\022A\n\026candi" +
      "dateTimeShiftPref\030\r \001(\0132!.in.trujobs.pro",
      "to.TimeShiftObject\022F\n\022candidateEducation" +
      "\030\016 \001(\0132*.in.trujobs.proto.CandidateEduca" +
      "tionObject\022 \n\030candidateTotalExperience\030\017" +
      " \001(\005\022\037\n\027candidateCurrentCompany\030\020 \001(\t\022\032\n" +
      "\022candidateDobMillis\030\021 \001(\003\022\033\n\023candidateIs" +
      "Employed\030\022 \001(\005\022B\n\023languageKnownObject\030\023 " +
      "\003(\0132%.in.trujobs.proto.LanguageKnownObje" +
      "ct\022D\n\024candidateSkillObject\030\024 \003(\0132&.in.tr" +
      "ujobs.proto.CandidateSkillObject\022@\n\027cand" +
      "idateCurrentJobRole\030\025 \001(\0132\037.in.trujobs.p",
      "roto.JobRoleObject\"-\n\030GetJobPostDetailsR" +
      "equest\022\021\n\tjobPostId\030\001 \001(\003\"\363\001\n\031GetJobPost" +
      "DetailsResponse\022B\n\006status\030\001 \001(\01622.in.tru" +
      "jobs.proto.GetJobPostDetailsResponse.Sta" +
      "tus\0220\n\007jobPost\030\002 \001(\0132\037.in.trujobs.proto." +
      "JobPostObject\0220\n\007company\030\003 \001(\0132\037.in.truj" +
      "obs.proto.CompanyObject\".\n\006Status\022\013\n\007UNK" +
      "NOWN\020\000\022\013\n\007SUCCESS\020\001\022\n\n\006NO_JOB\020\002\"\346\002\n\rComp" +
      "anyObject\022\021\n\tcompanyId\030\001 \001(\003\022\023\n\013companyN" +
      "ame\030\002 \001(\t\022\034\n\024companyEmployeeCount\030\003 \001(\t\022",
      "\026\n\016companyWebsite\030\004 \001(\t\022\032\n\022companyDescri" +
      "ption\030\005 \001(\t\022\026\n\016companyAddress\030\006 \001(\t\022\023\n\013c" +
      "ompanyLogo\030\007 \001(\t\0228\n\013companyType\030\t \001(\0132#." +
      "in.trujobs.proto.CompanyTypeObject\0229\n\017co" +
      "mpanyLocality\030\n \001(\0132 .in.trujobs.proto.L" +
      "ocalityObject\0229\n\020companyOtherJobs\030\013 \003(\0132" +
      "\037.in.trujobs.proto.JobPostObject\"C\n\021Comp" +
      "anyTypeObject\022\025\n\rcompanyTypeId\030\001 \001(\003\022\027\n\017" +
      "companyTypeName\030\002 \001(\t\"~\n\023HomeLocalityReq" +
      "uest\022\013\n\003lat\030\001 \001(\001\022\013\n\003lng\030\002 \001(\001\022\014\n\004name\030\003",
      " \001(\t\022\017\n\007address\030\004 \001(\t\022\030\n\020candidate_mobil" +
      "e\030\005 \001(\t\022\024\n\014candidate_id\030\006 \001(\003\"\232\001\n\024HomeLo" +
      "calityResponse\022=\n\006status\030\001 \001(\0162-.in.truj" +
      "obs.proto.HomeLocalityResponse.Status\"C\n" +
      "\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAI" +
      "LURE\020\002\022\022\n\016USER_NOT_FOUND\020\003\"\310\001\n\030Candidate" +
      "EducationObject\0224\n\teducation\030\001 \001(\0132!.in." +
      "trujobs.proto.EducationObject\022.\n\006degree\030" +
      "\002 \001(\0132\036.in.trujobs.proto.DegreeObject\022\032\n" +
      "\022candidateInstitute\030\003 \001(\t\022*\n\"candidateEd",
      "ucationCompletionStatus\030\004 \001(\005\"4\n\014DegreeO" +
      "bject\022\020\n\010degreeId\030\001 \001(\003\022\022\n\ndegreeName\030\002 " +
      "\001(\t\"7\n\033CandidateAppliedJobsRequest\022\030\n\020ca" +
      "ndidate_mobile\030\001 \001(\t\"\326\001\n\034CandidateApplie" +
      "dJobsResponse\022E\n\006status\030\001 \001(\01625.in.trujo" +
      "bs.proto.CandidateAppliedJobsResponse.St" +
      "atus\022>\n\016jobApplication\030\002 \003(\0132&.in.trujob" +
      "s.proto.JobApplicationObject\"/\n\006Status\022\013" +
      "\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\"\304\001" +
      "\n\024JobApplicationObject\022\030\n\020jobApplication",
      "Id\030\001 \001(\003\022#\n\033jobApplicationAppliedMillis\030" +
      "\002 \001(\003\0220\n\007jobPost\030\003 \001(\0132\037.in.trujobs.prot" +
      "o.JobPostObject\022;\n\021preScreenLocation\030\004 \001" +
      "(\0132 .in.trujobs.proto.LocalityObject\"\201\002\n" +
      "\"UpdateCandidateBasicProfileRequest\022\030\n\020c" +
      "andidate_mobile\030\001 \001(\t\022\034\n\024candidate_first" +
      "_name\030\002 \001(\t\022\033\n\023candidate_last_name\030\003 \001(\t" +
      "\022 \n\030candidate_timeshift_pref\030\004 \001(\003\022\030\n\020ca" +
      "ndidate_gender\030\005 \001(\005\022\024\n\014candidateDOB\030\006 \001" +
      "(\t\0224\n\013jobRolePref\030\007 \003(\0132\037.in.trujobs.pro",
      "to.JobRoleObject\"\212\003\n\'UpdateCandidateExpe" +
      "rienceProfileRequest\022\030\n\020candidate_mobile" +
      "\030\001 \001(\t\022\"\n\032candidate_total_experience\030\002 \001" +
      "(\005\022\035\n\025candidate_is_employed\030\003 \001(\005\022!\n\031can" +
      "didate_current_company\030\004 \001(\t\022 \n\030candidat" +
      "e_current_salary\030\005 \001(\003\0229\n\020current_job_ro" +
      "le\030\006 \001(\0132\037.in.trujobs.proto.JobRoleObjec" +
      "t\022A\n\022candidate_language\030\007 \003(\0132%.in.trujo" +
      "bs.proto.LanguageKnownObject\022?\n\017candidat" +
      "e_skill\030\010 \003(\0132&.in.trujobs.proto.Candida",
      "teSkillObject\"\325\001\n&UpdateCandidateEducati" +
      "onProfileRequest\022\030\n\020candidate_mobile\030\001 \001" +
      "(\t\022!\n\031candidate_education_level\030\002 \001(\003\022\030\n" +
      "\020candidate_degree\030\003 \001(\003\022%\n\035candidate_edu" +
      "cation_institute\030\004 \001(\t\022-\n%candidate_educ" +
      "ation_completion_status\030\005 \001(\005\"\244\001\n#Update" +
      "CandidateBasicProfileResponse\022L\n\006status\030" +
      "\001 \001(\0162<.in.trujobs.proto.UpdateCandidate" +
      "BasicProfileResponse.Status\"/\n\006Status\022\013\n" +
      "\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\"\344\001\n",
      "&GetCandidateBasicProfileStaticResponse\022" +
      "O\n\006status\030\001 \001(\0162?.in.trujobs.proto.GetCa" +
      "ndidateBasicProfileStaticResponse.Status" +
      "\0228\n\rtimeShiftList\030\002 \003(\0132!.in.trujobs.pro" +
      "to.TimeShiftObject\"/\n\006Status\022\013\n\007UNKNOWN\020" +
      "\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\"\324\002\n+GetCandi" +
      "dateExperienceProfileStaticResponse\022T\n\006s" +
      "tatus\030\001 \001(\0162D.in.trujobs.proto.GetCandid" +
      "ateExperienceProfileStaticResponse.Statu" +
      "s\0228\n\016languageObject\030\002 \003(\0132 .in.trujobs.p",
      "roto.LanguageObject\0222\n\013skillObject\030\003 \003(\013" +
      "2\035.in.trujobs.proto.SkillObject\0220\n\007jobRo" +
      "le\030\004 \003(\0132\037.in.trujobs.proto.JobRoleObjec" +
      "t\"/\n\006Status\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n" +
      "\007FAILURE\020\002\"\244\002\n*GetCandidateEducationProf" +
      "ileStaticResponse\022S\n\006status\030\001 \001(\0162C.in.t" +
      "rujobs.proto.GetCandidateEducationProfil" +
      "eStaticResponse.Status\0224\n\014degreeObject\030\002" +
      " \003(\0132\036.in.trujobs.proto.DegreeObject\022:\n\017" +
      "educationObject\030\003 \003(\0132!.in.trujobs.proto",
      ".EducationObject\"/\n\006Status\022\013\n\007UNKNOWN\020\000\022" +
      "\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\":\n\016LanguageObj" +
      "ect\022\022\n\nlanguageId\030\001 \001(\005\022\024\n\014languageName\030" +
      "\002 \001(\t\"H\n\013SkillObject\022\017\n\007skillId\030\001 \001(\005\022\021\n" +
      "\tskillName\030\002 \001(\t\022\025\n\rskillQuestion\030\003 \001(\t\"" +
      "|\n\023LanguageKnownObject\022\027\n\017languageKnownI" +
      "d\030\001 \001(\005\022\032\n\022languageUnderstand\030\002 \001(\005\022\025\n\rl" +
      "anguageSpeak\030\003 \001(\005\022\031\n\021languageReadWrite\030" +
      "\004 \001(\005\"7\n\024CandidateSkillObject\022\017\n\007skillId" +
      "\030\001 \001(\005\022\016\n\006answer\030\002 \001(\010B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_in_trujobs_proto_TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_in_trujobs_proto_TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_TestMessage_descriptor,
        new java.lang.String[] { "TestName", "TestPage", });
    internal_static_in_trujobs_proto_LogInRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_in_trujobs_proto_LogInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LogInRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "CandidatePassword", });
    internal_static_in_trujobs_proto_LogInResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_in_trujobs_proto_LogInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LogInResponse_descriptor,
        new java.lang.String[] { "Status", "LeadId", "CandidateId", "CandidateGender", "CandidateFirstName", "CandidateLastName", "CandidateIsAssessed", "SessionId", "SessionExpiryMillis", "MinProfile", "CandidateJobPrefStatus", "CandidateHomeLocalityStatus", });
    internal_static_in_trujobs_proto_SignUpRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_in_trujobs_proto_SignUpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_SignUpRequest_descriptor,
        new java.lang.String[] { "Name", "Mobile", });
    internal_static_in_trujobs_proto_SignUpResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_in_trujobs_proto_SignUpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_SignUpResponse_descriptor,
        new java.lang.String[] { "Status", "GeneratedOtp", });
    internal_static_in_trujobs_proto_ResetPasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_in_trujobs_proto_ResetPasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ResetPasswordRequest_descriptor,
        new java.lang.String[] { "Mobile", "Password", });
    internal_static_in_trujobs_proto_ResetPasswordResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_in_trujobs_proto_ResetPasswordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ResetPasswordResponse_descriptor,
        new java.lang.String[] { "Status", "Otp", });
    internal_static_in_trujobs_proto_JobRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_in_trujobs_proto_JobRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobRoleResponse_descriptor,
        new java.lang.String[] { "JobRole", });
    internal_static_in_trujobs_proto_JobRoleObject_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_in_trujobs_proto_JobRoleObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobRoleObject_descriptor,
        new java.lang.String[] { "JobRoleId", "JobRoleName", "JobRoleIcon", });
    internal_static_in_trujobs_proto_JobPostResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_in_trujobs_proto_JobPostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobPostResponse_descriptor,
        new java.lang.String[] { "JobPost", });
    internal_static_in_trujobs_proto_JobPostObject_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_in_trujobs_proto_JobPostObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobPostObject_descriptor,
        new java.lang.String[] { "JobPostId", "JobPostTitle", "JobPostCompanyName", "JobPostMinSalary", "JobPostMaxSalary", "JobPostLocality", "JobPostCompanyLogo", "JobPostExperience", "JobPostShift", "Vacancies", "JobPostDescription", "JobPostIncentives", "JobPostMinRequirements", "JobPostAddress", "JobPostWorkFromHome", "JobPostWorkingDays", "Education", "JobRole", "JobPostCreationMillis", "JobPostStartTime", "JobPostEndTime", });
    internal_static_in_trujobs_proto_JobPostDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_in_trujobs_proto_JobPostDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobPostDetailRequest_descriptor,
        new java.lang.String[] { "JobPostId", });
    internal_static_in_trujobs_proto_LocalityObject_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_in_trujobs_proto_LocalityObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LocalityObject_descriptor,
        new java.lang.String[] { "LocalityId", "LocalityName", });
    internal_static_in_trujobs_proto_ExperienceObject_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_in_trujobs_proto_ExperienceObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ExperienceObject_descriptor,
        new java.lang.String[] { "ExperienceId", "ExperienceType", });
    internal_static_in_trujobs_proto_EducationObject_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_in_trujobs_proto_EducationObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_EducationObject_descriptor,
        new java.lang.String[] { "EducationId", "EducationName", });
    internal_static_in_trujobs_proto_TimeShiftObject_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_in_trujobs_proto_TimeShiftObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_TimeShiftObject_descriptor,
        new java.lang.String[] { "TimeShiftId", "TimeShiftName", });
    internal_static_in_trujobs_proto_ApplyJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_in_trujobs_proto_ApplyJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ApplyJobRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "JobPostId", "LocalityId", });
    internal_static_in_trujobs_proto_ApplyJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_in_trujobs_proto_ApplyJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_ApplyJobResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_AddJobRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_in_trujobs_proto_AddJobRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_AddJobRoleRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "JobRolePrefOneId", "JobRolePrefTwoId", "JobRolePrefThreeId", });
    internal_static_in_trujobs_proto_AddJobRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_in_trujobs_proto_AddJobRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_AddJobRoleResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_CandidateInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_in_trujobs_proto_CandidateInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateInformationRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", });
    internal_static_in_trujobs_proto_GetCandidateInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_in_trujobs_proto_GetCandidateInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetCandidateInformationResponse_descriptor,
        new java.lang.String[] { "Status", "Candidate", "JobRoles", });
    internal_static_in_trujobs_proto_CandidateObject_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_in_trujobs_proto_CandidateObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateObject_descriptor,
        new java.lang.String[] { "CandidateId", "CandidateFirstName", "CandidateLastName", "CandidateIsAssessed", "CandidateMinProfileComplete", "CandidateGender", "CandidateMobile", "CandidateAge", "CandidateLastWithdrawnSalary", "CandidateHomelocality", "CandidateLocationPref", "CandidateJobRolePref", "CandidateTimeShiftPref", "CandidateEducation", "CandidateTotalExperience", "CandidateCurrentCompany", "CandidateDobMillis", "CandidateIsEmployed", "LanguageKnownObject", "CandidateSkillObject", "CandidateCurrentJobRole", });
    internal_static_in_trujobs_proto_GetJobPostDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_in_trujobs_proto_GetJobPostDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetJobPostDetailsRequest_descriptor,
        new java.lang.String[] { "JobPostId", });
    internal_static_in_trujobs_proto_GetJobPostDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_in_trujobs_proto_GetJobPostDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetJobPostDetailsResponse_descriptor,
        new java.lang.String[] { "Status", "JobPost", "Company", });
    internal_static_in_trujobs_proto_CompanyObject_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_in_trujobs_proto_CompanyObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CompanyObject_descriptor,
        new java.lang.String[] { "CompanyId", "CompanyName", "CompanyEmployeeCount", "CompanyWebsite", "CompanyDescription", "CompanyAddress", "CompanyLogo", "CompanyType", "CompanyLocality", "CompanyOtherJobs", });
    internal_static_in_trujobs_proto_CompanyTypeObject_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_in_trujobs_proto_CompanyTypeObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CompanyTypeObject_descriptor,
        new java.lang.String[] { "CompanyTypeId", "CompanyTypeName", });
    internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_in_trujobs_proto_HomeLocalityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor,
        new java.lang.String[] { "Lat", "Lng", "Name", "Address", "CandidateMobile", "CandidateId", });
    internal_static_in_trujobs_proto_HomeLocalityResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_in_trujobs_proto_HomeLocalityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_HomeLocalityResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_CandidateEducationObject_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_in_trujobs_proto_CandidateEducationObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateEducationObject_descriptor,
        new java.lang.String[] { "Education", "Degree", "CandidateInstitute", "CandidateEducationCompletionStatus", });
    internal_static_in_trujobs_proto_DegreeObject_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_in_trujobs_proto_DegreeObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_DegreeObject_descriptor,
        new java.lang.String[] { "DegreeId", "DegreeName", });
    internal_static_in_trujobs_proto_CandidateAppliedJobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_in_trujobs_proto_CandidateAppliedJobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateAppliedJobsRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", });
    internal_static_in_trujobs_proto_CandidateAppliedJobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_in_trujobs_proto_CandidateAppliedJobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateAppliedJobsResponse_descriptor,
        new java.lang.String[] { "Status", "JobApplication", });
    internal_static_in_trujobs_proto_JobApplicationObject_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_in_trujobs_proto_JobApplicationObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_JobApplicationObject_descriptor,
        new java.lang.String[] { "JobApplicationId", "JobApplicationAppliedMillis", "JobPost", "PreScreenLocation", });
    internal_static_in_trujobs_proto_UpdateCandidateBasicProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_in_trujobs_proto_UpdateCandidateBasicProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_UpdateCandidateBasicProfileRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "CandidateFirstName", "CandidateLastName", "CandidateTimeshiftPref", "CandidateGender", "CandidateDOB", "JobRolePref", });
    internal_static_in_trujobs_proto_UpdateCandidateExperienceProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_in_trujobs_proto_UpdateCandidateExperienceProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_UpdateCandidateExperienceProfileRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "CandidateTotalExperience", "CandidateIsEmployed", "CandidateCurrentCompany", "CandidateCurrentSalary", "CurrentJobRole", "CandidateLanguage", "CandidateSkill", });
    internal_static_in_trujobs_proto_UpdateCandidateEducationProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_in_trujobs_proto_UpdateCandidateEducationProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_UpdateCandidateEducationProfileRequest_descriptor,
        new java.lang.String[] { "CandidateMobile", "CandidateEducationLevel", "CandidateDegree", "CandidateEducationInstitute", "CandidateEducationCompletionStatus", });
    internal_static_in_trujobs_proto_UpdateCandidateBasicProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_in_trujobs_proto_UpdateCandidateBasicProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_UpdateCandidateBasicProfileResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_in_trujobs_proto_GetCandidateBasicProfileStaticResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_in_trujobs_proto_GetCandidateBasicProfileStaticResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetCandidateBasicProfileStaticResponse_descriptor,
        new java.lang.String[] { "Status", "TimeShiftList", });
    internal_static_in_trujobs_proto_GetCandidateExperienceProfileStaticResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_in_trujobs_proto_GetCandidateExperienceProfileStaticResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetCandidateExperienceProfileStaticResponse_descriptor,
        new java.lang.String[] { "Status", "LanguageObject", "SkillObject", "JobRole", });
    internal_static_in_trujobs_proto_GetCandidateEducationProfileStaticResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_in_trujobs_proto_GetCandidateEducationProfileStaticResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_GetCandidateEducationProfileStaticResponse_descriptor,
        new java.lang.String[] { "Status", "DegreeObject", "EducationObject", });
    internal_static_in_trujobs_proto_LanguageObject_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_in_trujobs_proto_LanguageObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LanguageObject_descriptor,
        new java.lang.String[] { "LanguageId", "LanguageName", });
    internal_static_in_trujobs_proto_SkillObject_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_in_trujobs_proto_SkillObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_SkillObject_descriptor,
        new java.lang.String[] { "SkillId", "SkillName", "SkillQuestion", });
    internal_static_in_trujobs_proto_LanguageKnownObject_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_in_trujobs_proto_LanguageKnownObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_LanguageKnownObject_descriptor,
        new java.lang.String[] { "LanguageKnownId", "LanguageUnderstand", "LanguageSpeak", "LanguageReadWrite", });
    internal_static_in_trujobs_proto_CandidateSkillObject_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_in_trujobs_proto_CandidateSkillObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_in_trujobs_proto_CandidateSkillObject_descriptor,
        new java.lang.String[] { "SkillId", "Answer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
