// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface GetInterviewSlotsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.GetInterviewSlotsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 jobPostId = 1;</code>
   */
  long getJobPostId();
}
