// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.HomeLocalityRequest}
 */
public  final class HomeLocalityRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.HomeLocalityRequest)
    HomeLocalityRequestOrBuilder {
  // Use HomeLocalityRequest.newBuilder() to construct.
  private HomeLocalityRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HomeLocalityRequest() {
    localityId_ = 0L;
    lat_ = 0D;
    lng_ = 0D;
    localityName_ = "";
    placeId_ = "";
    candidateMobile_ = "";
    candidateId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private HomeLocalityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            localityId_ = input.readInt64();
            break;
          }
          case 17: {

            lat_ = input.readDouble();
            break;
          }
          case 25: {

            lng_ = input.readDouble();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            localityName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            placeId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            candidateMobile_ = s;
            break;
          }
          case 56: {

            candidateId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_HomeLocalityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.HomeLocalityRequest.class, in.trujobs.proto.HomeLocalityRequest.Builder.class);
  }

  public static final int LOCALITYID_FIELD_NUMBER = 1;
  private long localityId_;
  /**
   * <code>optional int64 localityId = 1;</code>
   */
  public long getLocalityId() {
    return localityId_;
  }

  public static final int LAT_FIELD_NUMBER = 2;
  private double lat_;
  /**
   * <code>optional double lat = 2;</code>
   */
  public double getLat() {
    return lat_;
  }

  public static final int LNG_FIELD_NUMBER = 3;
  private double lng_;
  /**
   * <code>optional double lng = 3;</code>
   */
  public double getLng() {
    return lng_;
  }

  public static final int LOCALITY_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object localityName_;
  /**
   * <code>optional string locality_name = 4;</code>
   */
  public java.lang.String getLocalityName() {
    java.lang.Object ref = localityName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localityName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string locality_name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLocalityNameBytes() {
    java.lang.Object ref = localityName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localityName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLACE_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object placeId_;
  /**
   * <code>optional string place_id = 5;</code>
   */
  public java.lang.String getPlaceId() {
    java.lang.Object ref = placeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      placeId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string place_id = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPlaceIdBytes() {
    java.lang.Object ref = placeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      placeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATE_MOBILE_FIELD_NUMBER = 6;
  private volatile java.lang.Object candidateMobile_;
  /**
   * <code>optional string candidate_mobile = 6;</code>
   */
  public java.lang.String getCandidateMobile() {
    java.lang.Object ref = candidateMobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateMobile_ = s;
      return s;
    }
  }
  /**
   * <code>optional string candidate_mobile = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCandidateMobileBytes() {
    java.lang.Object ref = candidateMobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateMobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATE_ID_FIELD_NUMBER = 7;
  private long candidateId_;
  /**
   * <code>optional int64 candidate_id = 7;</code>
   */
  public long getCandidateId() {
    return candidateId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (localityId_ != 0L) {
      output.writeInt64(1, localityId_);
    }
    if (lat_ != 0D) {
      output.writeDouble(2, lat_);
    }
    if (lng_ != 0D) {
      output.writeDouble(3, lng_);
    }
    if (!getLocalityNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, localityName_);
    }
    if (!getPlaceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, placeId_);
    }
    if (!getCandidateMobileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, candidateMobile_);
    }
    if (candidateId_ != 0L) {
      output.writeInt64(7, candidateId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (localityId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, localityId_);
    }
    if (lat_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, lat_);
    }
    if (lng_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, lng_);
    }
    if (!getLocalityNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, localityName_);
    }
    if (!getPlaceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, placeId_);
    }
    if (!getCandidateMobileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, candidateMobile_);
    }
    if (candidateId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, candidateId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.HomeLocalityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.HomeLocalityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.HomeLocalityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.HomeLocalityRequest)
      in.trujobs.proto.HomeLocalityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_HomeLocalityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.HomeLocalityRequest.class, in.trujobs.proto.HomeLocalityRequest.Builder.class);
    }

    // Construct using in.trujobs.proto.HomeLocalityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      localityId_ = 0L;

      lat_ = 0D;

      lng_ = 0D;

      localityName_ = "";

      placeId_ = "";

      candidateMobile_ = "";

      candidateId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_HomeLocalityRequest_descriptor;
    }

    public in.trujobs.proto.HomeLocalityRequest getDefaultInstanceForType() {
      return in.trujobs.proto.HomeLocalityRequest.getDefaultInstance();
    }

    public in.trujobs.proto.HomeLocalityRequest build() {
      in.trujobs.proto.HomeLocalityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.HomeLocalityRequest buildPartial() {
      in.trujobs.proto.HomeLocalityRequest result = new in.trujobs.proto.HomeLocalityRequest(this);
      result.localityId_ = localityId_;
      result.lat_ = lat_;
      result.lng_ = lng_;
      result.localityName_ = localityName_;
      result.placeId_ = placeId_;
      result.candidateMobile_ = candidateMobile_;
      result.candidateId_ = candidateId_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.HomeLocalityRequest) {
        return mergeFrom((in.trujobs.proto.HomeLocalityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.HomeLocalityRequest other) {
      if (other == in.trujobs.proto.HomeLocalityRequest.getDefaultInstance()) return this;
      if (other.getLocalityId() != 0L) {
        setLocalityId(other.getLocalityId());
      }
      if (other.getLat() != 0D) {
        setLat(other.getLat());
      }
      if (other.getLng() != 0D) {
        setLng(other.getLng());
      }
      if (!other.getLocalityName().isEmpty()) {
        localityName_ = other.localityName_;
        onChanged();
      }
      if (!other.getPlaceId().isEmpty()) {
        placeId_ = other.placeId_;
        onChanged();
      }
      if (!other.getCandidateMobile().isEmpty()) {
        candidateMobile_ = other.candidateMobile_;
        onChanged();
      }
      if (other.getCandidateId() != 0L) {
        setCandidateId(other.getCandidateId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.HomeLocalityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.HomeLocalityRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long localityId_ ;
    /**
     * <code>optional int64 localityId = 1;</code>
     */
    public long getLocalityId() {
      return localityId_;
    }
    /**
     * <code>optional int64 localityId = 1;</code>
     */
    public Builder setLocalityId(long value) {
      
      localityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 localityId = 1;</code>
     */
    public Builder clearLocalityId() {
      
      localityId_ = 0L;
      onChanged();
      return this;
    }

    private double lat_ ;
    /**
     * <code>optional double lat = 2;</code>
     */
    public double getLat() {
      return lat_;
    }
    /**
     * <code>optional double lat = 2;</code>
     */
    public Builder setLat(double value) {
      
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double lat = 2;</code>
     */
    public Builder clearLat() {
      
      lat_ = 0D;
      onChanged();
      return this;
    }

    private double lng_ ;
    /**
     * <code>optional double lng = 3;</code>
     */
    public double getLng() {
      return lng_;
    }
    /**
     * <code>optional double lng = 3;</code>
     */
    public Builder setLng(double value) {
      
      lng_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double lng = 3;</code>
     */
    public Builder clearLng() {
      
      lng_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object localityName_ = "";
    /**
     * <code>optional string locality_name = 4;</code>
     */
    public java.lang.String getLocalityName() {
      java.lang.Object ref = localityName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localityName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string locality_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocalityNameBytes() {
      java.lang.Object ref = localityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string locality_name = 4;</code>
     */
    public Builder setLocalityName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      localityName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string locality_name = 4;</code>
     */
    public Builder clearLocalityName() {
      
      localityName_ = getDefaultInstance().getLocalityName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string locality_name = 4;</code>
     */
    public Builder setLocalityNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      localityName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object placeId_ = "";
    /**
     * <code>optional string place_id = 5;</code>
     */
    public java.lang.String getPlaceId() {
      java.lang.Object ref = placeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        placeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string place_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPlaceIdBytes() {
      java.lang.Object ref = placeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        placeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string place_id = 5;</code>
     */
    public Builder setPlaceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      placeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string place_id = 5;</code>
     */
    public Builder clearPlaceId() {
      
      placeId_ = getDefaultInstance().getPlaceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string place_id = 5;</code>
     */
    public Builder setPlaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      placeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object candidateMobile_ = "";
    /**
     * <code>optional string candidate_mobile = 6;</code>
     */
    public java.lang.String getCandidateMobile() {
      java.lang.Object ref = candidateMobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateMobile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string candidate_mobile = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateMobileBytes() {
      java.lang.Object ref = candidateMobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string candidate_mobile = 6;</code>
     */
    public Builder setCandidateMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      candidateMobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidate_mobile = 6;</code>
     */
    public Builder clearCandidateMobile() {
      
      candidateMobile_ = getDefaultInstance().getCandidateMobile();
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidate_mobile = 6;</code>
     */
    public Builder setCandidateMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      candidateMobile_ = value;
      onChanged();
      return this;
    }

    private long candidateId_ ;
    /**
     * <code>optional int64 candidate_id = 7;</code>
     */
    public long getCandidateId() {
      return candidateId_;
    }
    /**
     * <code>optional int64 candidate_id = 7;</code>
     */
    public Builder setCandidateId(long value) {
      
      candidateId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 candidate_id = 7;</code>
     */
    public Builder clearCandidateId() {
      
      candidateId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.HomeLocalityRequest)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.HomeLocalityRequest)
  private static final in.trujobs.proto.HomeLocalityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.HomeLocalityRequest();
  }

  public static in.trujobs.proto.HomeLocalityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HomeLocalityRequest>
      PARSER = new com.google.protobuf.AbstractParser<HomeLocalityRequest>() {
    public HomeLocalityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new HomeLocalityRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<HomeLocalityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HomeLocalityRequest> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.HomeLocalityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

