// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface JobPostWorkFlowStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.JobPostWorkFlowStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 statusId = 1;</code>
   */
  long getStatusId();

  /**
   * <code>optional string statusTitle = 2;</code>
   */
  java.lang.String getStatusTitle();
  /**
   * <code>optional string statusTitle = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusTitleBytes();
}
