// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.JobRole}
 */
public  final class JobRole extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.JobRole)
    JobRoleOrBuilder {
  // Use JobRole.newBuilder() to construct.
  private JobRole(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JobRole() {
    jobRoleId_ = "";
    jobRoleName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JobRole(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            jobRoleId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            jobRoleName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_JobRole_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_JobRole_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.JobRole.class, in.trujobs.proto.JobRole.Builder.class);
  }

  public static final int JOBROLEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object jobRoleId_;
  /**
   * <code>optional string jobRoleId = 1;</code>
   */
  public java.lang.String getJobRoleId() {
    java.lang.Object ref = jobRoleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobRoleId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string jobRoleId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getJobRoleIdBytes() {
    java.lang.Object ref = jobRoleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobRoleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOBROLENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object jobRoleName_;
  /**
   * <code>optional string jobRoleName = 2;</code>
   */
  public java.lang.String getJobRoleName() {
    java.lang.Object ref = jobRoleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobRoleName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string jobRoleName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getJobRoleNameBytes() {
    java.lang.Object ref = jobRoleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobRoleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJobRoleIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, jobRoleId_);
    }
    if (!getJobRoleNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, jobRoleName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJobRoleIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jobRoleId_);
    }
    if (!getJobRoleNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, jobRoleName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.JobRole parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.JobRole parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.JobRole parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.JobRole parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.JobRole parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.JobRole parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.JobRole parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.JobRole parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.JobRole parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.JobRole parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.JobRole prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.JobRole}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.JobRole)
      in.trujobs.proto.JobRoleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_JobRole_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_JobRole_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.JobRole.class, in.trujobs.proto.JobRole.Builder.class);
    }

    // Construct using in.trujobs.proto.JobRole.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      jobRoleId_ = "";

      jobRoleName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_JobRole_descriptor;
    }

    public in.trujobs.proto.JobRole getDefaultInstanceForType() {
      return in.trujobs.proto.JobRole.getDefaultInstance();
    }

    public in.trujobs.proto.JobRole build() {
      in.trujobs.proto.JobRole result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.JobRole buildPartial() {
      in.trujobs.proto.JobRole result = new in.trujobs.proto.JobRole(this);
      result.jobRoleId_ = jobRoleId_;
      result.jobRoleName_ = jobRoleName_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.JobRole) {
        return mergeFrom((in.trujobs.proto.JobRole)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.JobRole other) {
      if (other == in.trujobs.proto.JobRole.getDefaultInstance()) return this;
      if (!other.getJobRoleId().isEmpty()) {
        jobRoleId_ = other.jobRoleId_;
        onChanged();
      }
      if (!other.getJobRoleName().isEmpty()) {
        jobRoleName_ = other.jobRoleName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.JobRole parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.JobRole) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object jobRoleId_ = "";
    /**
     * <code>optional string jobRoleId = 1;</code>
     */
    public java.lang.String getJobRoleId() {
      java.lang.Object ref = jobRoleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobRoleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string jobRoleId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJobRoleIdBytes() {
      java.lang.Object ref = jobRoleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobRoleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string jobRoleId = 1;</code>
     */
    public Builder setJobRoleId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobRoleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string jobRoleId = 1;</code>
     */
    public Builder clearJobRoleId() {
      
      jobRoleId_ = getDefaultInstance().getJobRoleId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string jobRoleId = 1;</code>
     */
    public Builder setJobRoleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobRoleId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobRoleName_ = "";
    /**
     * <code>optional string jobRoleName = 2;</code>
     */
    public java.lang.String getJobRoleName() {
      java.lang.Object ref = jobRoleName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobRoleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string jobRoleName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJobRoleNameBytes() {
      java.lang.Object ref = jobRoleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobRoleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string jobRoleName = 2;</code>
     */
    public Builder setJobRoleName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobRoleName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string jobRoleName = 2;</code>
     */
    public Builder clearJobRoleName() {
      
      jobRoleName_ = getDefaultInstance().getJobRoleName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string jobRoleName = 2;</code>
     */
    public Builder setJobRoleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobRoleName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.JobRole)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.JobRole)
  private static final in.trujobs.proto.JobRole DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.JobRole();
  }

  public static in.trujobs.proto.JobRole getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobRole>
      PARSER = new com.google.protobuf.AbstractParser<JobRole>() {
    public JobRole parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new JobRole(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<JobRole> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobRole> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.JobRole getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

