// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface JobSearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.JobSearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double latitude = 1;</code>
   */
  double getLatitude();

  /**
   * <code>optional double longitude = 2;</code>
   */
  double getLongitude();

  /**
   * <code>optional string candidate_mobile = 3;</code>
   */
  java.lang.String getCandidateMobile();
  /**
   * <code>optional string candidate_mobile = 3;</code>
   */
  com.google.protobuf.ByteString
      getCandidateMobileBytes();

  /**
   * <code>optional .in.trujobs.proto.JobFilterRequest jobFilterRequest = 4;</code>
   */
  boolean hasJobFilterRequest();
  /**
   * <code>optional .in.trujobs.proto.JobFilterRequest jobFilterRequest = 4;</code>
   */
  in.trujobs.proto.JobFilterRequest getJobFilterRequest();
  /**
   * <code>optional .in.trujobs.proto.JobFilterRequest jobFilterRequest = 4;</code>
   */
  in.trujobs.proto.JobFilterRequestOrBuilder getJobFilterRequestOrBuilder();

  /**
   * <code>optional .in.trujobs.proto.JobSearchByJobRoleRequest jobSearchByJobRoleRequest = 5;</code>
   */
  boolean hasJobSearchByJobRoleRequest();
  /**
   * <code>optional .in.trujobs.proto.JobSearchByJobRoleRequest jobSearchByJobRoleRequest = 5;</code>
   */
  in.trujobs.proto.JobSearchByJobRoleRequest getJobSearchByJobRoleRequest();
  /**
   * <code>optional .in.trujobs.proto.JobSearchByJobRoleRequest jobSearchByJobRoleRequest = 5;</code>
   */
  in.trujobs.proto.JobSearchByJobRoleRequestOrBuilder getJobSearchByJobRoleRequestOrBuilder();
}
