// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface LanguageKnownObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.LanguageKnownObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 languageKnownId = 1;</code>
   */
  int getLanguageKnownId();

  /**
   * <code>optional int32 languageUnderstand = 2;</code>
   */
  int getLanguageUnderstand();

  /**
   * <code>optional int32 languageSpeak = 3;</code>
   */
  int getLanguageSpeak();

  /**
   * <code>optional int32 languageReadWrite = 4;</code>
   */
  int getLanguageReadWrite();
}
