// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.LastActiveValueObject}
 */
public  final class LastActiveValueObject extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.LastActiveValueObject)
    LastActiveValueObjectOrBuilder {
  // Use LastActiveValueObject.newBuilder() to construct.
  private LastActiveValueObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LastActiveValueObject() {
    lastActiveId_ = 0;
    lastActiveValue_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LastActiveValueObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            lastActiveId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            lastActiveValue_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_LastActiveValueObject_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_LastActiveValueObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.LastActiveValueObject.class, in.trujobs.proto.LastActiveValueObject.Builder.class);
  }

  public static final int LASTACTIVEID_FIELD_NUMBER = 1;
  private int lastActiveId_;
  /**
   * <code>optional int32 lastActiveId = 1;</code>
   */
  public int getLastActiveId() {
    return lastActiveId_;
  }

  public static final int LASTACTIVEVALUE_FIELD_NUMBER = 2;
  private volatile java.lang.Object lastActiveValue_;
  /**
   * <code>optional string lastActiveValue = 2;</code>
   */
  public java.lang.String getLastActiveValue() {
    java.lang.Object ref = lastActiveValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastActiveValue_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lastActiveValue = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLastActiveValueBytes() {
    java.lang.Object ref = lastActiveValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastActiveValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lastActiveId_ != 0) {
      output.writeInt32(1, lastActiveId_);
    }
    if (!getLastActiveValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, lastActiveValue_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lastActiveId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, lastActiveId_);
    }
    if (!getLastActiveValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lastActiveValue_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.LastActiveValueObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.LastActiveValueObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.LastActiveValueObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.LastActiveValueObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.LastActiveValueObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.LastActiveValueObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.LastActiveValueObject)
      in.trujobs.proto.LastActiveValueObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_LastActiveValueObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_LastActiveValueObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.LastActiveValueObject.class, in.trujobs.proto.LastActiveValueObject.Builder.class);
    }

    // Construct using in.trujobs.proto.LastActiveValueObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      lastActiveId_ = 0;

      lastActiveValue_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_LastActiveValueObject_descriptor;
    }

    public in.trujobs.proto.LastActiveValueObject getDefaultInstanceForType() {
      return in.trujobs.proto.LastActiveValueObject.getDefaultInstance();
    }

    public in.trujobs.proto.LastActiveValueObject build() {
      in.trujobs.proto.LastActiveValueObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.LastActiveValueObject buildPartial() {
      in.trujobs.proto.LastActiveValueObject result = new in.trujobs.proto.LastActiveValueObject(this);
      result.lastActiveId_ = lastActiveId_;
      result.lastActiveValue_ = lastActiveValue_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.LastActiveValueObject) {
        return mergeFrom((in.trujobs.proto.LastActiveValueObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.LastActiveValueObject other) {
      if (other == in.trujobs.proto.LastActiveValueObject.getDefaultInstance()) return this;
      if (other.getLastActiveId() != 0) {
        setLastActiveId(other.getLastActiveId());
      }
      if (!other.getLastActiveValue().isEmpty()) {
        lastActiveValue_ = other.lastActiveValue_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.LastActiveValueObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.LastActiveValueObject) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int lastActiveId_ ;
    /**
     * <code>optional int32 lastActiveId = 1;</code>
     */
    public int getLastActiveId() {
      return lastActiveId_;
    }
    /**
     * <code>optional int32 lastActiveId = 1;</code>
     */
    public Builder setLastActiveId(int value) {
      
      lastActiveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 lastActiveId = 1;</code>
     */
    public Builder clearLastActiveId() {
      
      lastActiveId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object lastActiveValue_ = "";
    /**
     * <code>optional string lastActiveValue = 2;</code>
     */
    public java.lang.String getLastActiveValue() {
      java.lang.Object ref = lastActiveValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastActiveValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lastActiveValue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastActiveValueBytes() {
      java.lang.Object ref = lastActiveValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastActiveValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastActiveValue = 2;</code>
     */
    public Builder setLastActiveValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastActiveValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastActiveValue = 2;</code>
     */
    public Builder clearLastActiveValue() {
      
      lastActiveValue_ = getDefaultInstance().getLastActiveValue();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastActiveValue = 2;</code>
     */
    public Builder setLastActiveValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastActiveValue_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.LastActiveValueObject)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.LastActiveValueObject)
  private static final in.trujobs.proto.LastActiveValueObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.LastActiveValueObject();
  }

  public static in.trujobs.proto.LastActiveValueObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LastActiveValueObject>
      PARSER = new com.google.protobuf.AbstractParser<LastActiveValueObject>() {
    public LastActiveValueObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new LastActiveValueObject(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<LastActiveValueObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LastActiveValueObject> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.LastActiveValueObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

