// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface NotGoingReasonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.NotGoingReasonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .in.trujobs.proto.ReasonObject reasonObject = 1;</code>
   */
  java.util.List<in.trujobs.proto.ReasonObject> 
      getReasonObjectList();
  /**
   * <code>repeated .in.trujobs.proto.ReasonObject reasonObject = 1;</code>
   */
  in.trujobs.proto.ReasonObject getReasonObject(int index);
  /**
   * <code>repeated .in.trujobs.proto.ReasonObject reasonObject = 1;</code>
   */
  int getReasonObjectCount();
  /**
   * <code>repeated .in.trujobs.proto.ReasonObject reasonObject = 1;</code>
   */
  java.util.List<? extends in.trujobs.proto.ReasonObjectOrBuilder> 
      getReasonObjectOrBuilderList();
  /**
   * <code>repeated .in.trujobs.proto.ReasonObject reasonObject = 1;</code>
   */
  in.trujobs.proto.ReasonObjectOrBuilder getReasonObjectOrBuilder(
      int index);
}
