// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.PreScreenEducationObject}
 */
public  final class PreScreenEducationObject extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.PreScreenEducationObject)
    PreScreenEducationObjectOrBuilder {
  // Use PreScreenEducationObject.newBuilder() to construct.
  private PreScreenEducationObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PreScreenEducationObject() {
    isMatching_ = false;
    propertyId_ = 0;
    propertyTitle_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PreScreenEducationObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isMatching_ = input.readBool();
            break;
          }
          case 16: {

            propertyId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            propertyTitle_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_PreScreenEducationObject_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_PreScreenEducationObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.PreScreenEducationObject.class, in.trujobs.proto.PreScreenEducationObject.Builder.class);
  }

  public static final int ISMATCHING_FIELD_NUMBER = 1;
  private boolean isMatching_;
  /**
   * <code>optional bool isMatching = 1;</code>
   */
  public boolean getIsMatching() {
    return isMatching_;
  }

  public static final int PROPERTYID_FIELD_NUMBER = 2;
  private int propertyId_;
  /**
   * <code>optional int32 propertyId = 2;</code>
   */
  public int getPropertyId() {
    return propertyId_;
  }

  public static final int PROPERTYTITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object propertyTitle_;
  /**
   * <code>optional string propertyTitle = 3;</code>
   */
  public java.lang.String getPropertyTitle() {
    java.lang.Object ref = propertyTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      propertyTitle_ = s;
      return s;
    }
  }
  /**
   * <code>optional string propertyTitle = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPropertyTitleBytes() {
    java.lang.Object ref = propertyTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      propertyTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isMatching_ != false) {
      output.writeBool(1, isMatching_);
    }
    if (propertyId_ != 0) {
      output.writeInt32(2, propertyId_);
    }
    if (!getPropertyTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, propertyTitle_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isMatching_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isMatching_);
    }
    if (propertyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, propertyId_);
    }
    if (!getPropertyTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, propertyTitle_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.PreScreenEducationObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.PreScreenEducationObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.PreScreenEducationObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.PreScreenEducationObject)
      in.trujobs.proto.PreScreenEducationObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_PreScreenEducationObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_PreScreenEducationObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.PreScreenEducationObject.class, in.trujobs.proto.PreScreenEducationObject.Builder.class);
    }

    // Construct using in.trujobs.proto.PreScreenEducationObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isMatching_ = false;

      propertyId_ = 0;

      propertyTitle_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_PreScreenEducationObject_descriptor;
    }

    public in.trujobs.proto.PreScreenEducationObject getDefaultInstanceForType() {
      return in.trujobs.proto.PreScreenEducationObject.getDefaultInstance();
    }

    public in.trujobs.proto.PreScreenEducationObject build() {
      in.trujobs.proto.PreScreenEducationObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.PreScreenEducationObject buildPartial() {
      in.trujobs.proto.PreScreenEducationObject result = new in.trujobs.proto.PreScreenEducationObject(this);
      result.isMatching_ = isMatching_;
      result.propertyId_ = propertyId_;
      result.propertyTitle_ = propertyTitle_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.PreScreenEducationObject) {
        return mergeFrom((in.trujobs.proto.PreScreenEducationObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.PreScreenEducationObject other) {
      if (other == in.trujobs.proto.PreScreenEducationObject.getDefaultInstance()) return this;
      if (other.getIsMatching() != false) {
        setIsMatching(other.getIsMatching());
      }
      if (other.getPropertyId() != 0) {
        setPropertyId(other.getPropertyId());
      }
      if (!other.getPropertyTitle().isEmpty()) {
        propertyTitle_ = other.propertyTitle_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.PreScreenEducationObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.PreScreenEducationObject) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isMatching_ ;
    /**
     * <code>optional bool isMatching = 1;</code>
     */
    public boolean getIsMatching() {
      return isMatching_;
    }
    /**
     * <code>optional bool isMatching = 1;</code>
     */
    public Builder setIsMatching(boolean value) {
      
      isMatching_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isMatching = 1;</code>
     */
    public Builder clearIsMatching() {
      
      isMatching_ = false;
      onChanged();
      return this;
    }

    private int propertyId_ ;
    /**
     * <code>optional int32 propertyId = 2;</code>
     */
    public int getPropertyId() {
      return propertyId_;
    }
    /**
     * <code>optional int32 propertyId = 2;</code>
     */
    public Builder setPropertyId(int value) {
      
      propertyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 propertyId = 2;</code>
     */
    public Builder clearPropertyId() {
      
      propertyId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object propertyTitle_ = "";
    /**
     * <code>optional string propertyTitle = 3;</code>
     */
    public java.lang.String getPropertyTitle() {
      java.lang.Object ref = propertyTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        propertyTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string propertyTitle = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPropertyTitleBytes() {
      java.lang.Object ref = propertyTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        propertyTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string propertyTitle = 3;</code>
     */
    public Builder setPropertyTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      propertyTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string propertyTitle = 3;</code>
     */
    public Builder clearPropertyTitle() {
      
      propertyTitle_ = getDefaultInstance().getPropertyTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string propertyTitle = 3;</code>
     */
    public Builder setPropertyTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      propertyTitle_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.PreScreenEducationObject)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.PreScreenEducationObject)
  private static final in.trujobs.proto.PreScreenEducationObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.PreScreenEducationObject();
  }

  public static in.trujobs.proto.PreScreenEducationObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreScreenEducationObject>
      PARSER = new com.google.protobuf.AbstractParser<PreScreenEducationObject>() {
    public PreScreenEducationObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new PreScreenEducationObject(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<PreScreenEducationObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreScreenEducationObject> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.PreScreenEducationObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

