// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.TimeShiftObject}
 */
public  final class TimeShiftObject extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.TimeShiftObject)
    TimeShiftObjectOrBuilder {
  // Use TimeShiftObject.newBuilder() to construct.
  private TimeShiftObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TimeShiftObject() {
    timeShiftId_ = 0L;
    timeShiftName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TimeShiftObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            timeShiftId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            timeShiftName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_TimeShiftObject_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_TimeShiftObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.TimeShiftObject.class, in.trujobs.proto.TimeShiftObject.Builder.class);
  }

  public static final int TIMESHIFTID_FIELD_NUMBER = 1;
  private long timeShiftId_;
  /**
   * <code>optional int64 timeShiftId = 1;</code>
   */
  public long getTimeShiftId() {
    return timeShiftId_;
  }

  public static final int TIMESHIFTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object timeShiftName_;
  /**
   * <code>optional string timeShiftName = 2;</code>
   */
  public java.lang.String getTimeShiftName() {
    java.lang.Object ref = timeShiftName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeShiftName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string timeShiftName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTimeShiftNameBytes() {
    java.lang.Object ref = timeShiftName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeShiftName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeShiftId_ != 0L) {
      output.writeInt64(1, timeShiftId_);
    }
    if (!getTimeShiftNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, timeShiftName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeShiftId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timeShiftId_);
    }
    if (!getTimeShiftNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, timeShiftName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.TimeShiftObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.TimeShiftObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.TimeShiftObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.TimeShiftObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.TimeShiftObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.TimeShiftObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.TimeShiftObject)
      in.trujobs.proto.TimeShiftObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_TimeShiftObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_TimeShiftObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.TimeShiftObject.class, in.trujobs.proto.TimeShiftObject.Builder.class);
    }

    // Construct using in.trujobs.proto.TimeShiftObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      timeShiftId_ = 0L;

      timeShiftName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_TimeShiftObject_descriptor;
    }

    public in.trujobs.proto.TimeShiftObject getDefaultInstanceForType() {
      return in.trujobs.proto.TimeShiftObject.getDefaultInstance();
    }

    public in.trujobs.proto.TimeShiftObject build() {
      in.trujobs.proto.TimeShiftObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.TimeShiftObject buildPartial() {
      in.trujobs.proto.TimeShiftObject result = new in.trujobs.proto.TimeShiftObject(this);
      result.timeShiftId_ = timeShiftId_;
      result.timeShiftName_ = timeShiftName_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.TimeShiftObject) {
        return mergeFrom((in.trujobs.proto.TimeShiftObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.TimeShiftObject other) {
      if (other == in.trujobs.proto.TimeShiftObject.getDefaultInstance()) return this;
      if (other.getTimeShiftId() != 0L) {
        setTimeShiftId(other.getTimeShiftId());
      }
      if (!other.getTimeShiftName().isEmpty()) {
        timeShiftName_ = other.timeShiftName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.TimeShiftObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.TimeShiftObject) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long timeShiftId_ ;
    /**
     * <code>optional int64 timeShiftId = 1;</code>
     */
    public long getTimeShiftId() {
      return timeShiftId_;
    }
    /**
     * <code>optional int64 timeShiftId = 1;</code>
     */
    public Builder setTimeShiftId(long value) {
      
      timeShiftId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 timeShiftId = 1;</code>
     */
    public Builder clearTimeShiftId() {
      
      timeShiftId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object timeShiftName_ = "";
    /**
     * <code>optional string timeShiftName = 2;</code>
     */
    public java.lang.String getTimeShiftName() {
      java.lang.Object ref = timeShiftName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeShiftName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string timeShiftName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeShiftNameBytes() {
      java.lang.Object ref = timeShiftName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeShiftName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string timeShiftName = 2;</code>
     */
    public Builder setTimeShiftName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeShiftName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string timeShiftName = 2;</code>
     */
    public Builder clearTimeShiftName() {
      
      timeShiftName_ = getDefaultInstance().getTimeShiftName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string timeShiftName = 2;</code>
     */
    public Builder setTimeShiftNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeShiftName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.TimeShiftObject)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.TimeShiftObject)
  private static final in.trujobs.proto.TimeShiftObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.TimeShiftObject();
  }

  public static in.trujobs.proto.TimeShiftObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeShiftObject>
      PARSER = new com.google.protobuf.AbstractParser<TimeShiftObject>() {
    public TimeShiftObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new TimeShiftObject(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<TimeShiftObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeShiftObject> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.TimeShiftObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

