// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface UpdateTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.UpdateTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string candidate_id = 1;</code>
   */
  java.lang.String getCandidateId();
  /**
   * <code>optional string candidate_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();

  /**
   * <code>optional string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
