// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.UpdateCandidateInterviewDetailRequest}
 */
public  final class UpdateCandidateInterviewDetailRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.UpdateCandidateInterviewDetailRequest)
    UpdateCandidateInterviewDetailRequestOrBuilder {
  // Use UpdateCandidateInterviewDetailRequest.newBuilder() to construct.
  private UpdateCandidateInterviewDetailRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateCandidateInterviewDetailRequest() {
    candidateMobile_ = "";
    timeSlotId_ = 0;
    jobPostId_ = 0L;
    scheduledInterviewDateInMills_ = 0L;
    isFinalFragment_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateCandidateInterviewDetailRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            candidateMobile_ = s;
            break;
          }
          case 16: {

            timeSlotId_ = input.readInt32();
            break;
          }
          case 32: {

            jobPostId_ = input.readInt64();
            break;
          }
          case 40: {

            scheduledInterviewDateInMills_ = input.readInt64();
            break;
          }
          case 48: {

            isFinalFragment_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateInterviewDetailRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateInterviewDetailRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.UpdateCandidateInterviewDetailRequest.class, in.trujobs.proto.UpdateCandidateInterviewDetailRequest.Builder.class);
  }

  public static final int CANDIDATE_MOBILE_FIELD_NUMBER = 1;
  private volatile java.lang.Object candidateMobile_;
  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  public java.lang.String getCandidateMobile() {
    java.lang.Object ref = candidateMobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateMobile_ = s;
      return s;
    }
  }
  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCandidateMobileBytes() {
    java.lang.Object ref = candidateMobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateMobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESLOTID_FIELD_NUMBER = 2;
  private int timeSlotId_;
  /**
   * <code>optional int32 timeSlotId = 2;</code>
   */
  public int getTimeSlotId() {
    return timeSlotId_;
  }

  public static final int JOBPOSTID_FIELD_NUMBER = 4;
  private long jobPostId_;
  /**
   * <code>optional int64 jobPostId = 4;</code>
   */
  public long getJobPostId() {
    return jobPostId_;
  }

  public static final int SCHEDULEDINTERVIEWDATEINMILLS_FIELD_NUMBER = 5;
  private long scheduledInterviewDateInMills_;
  /**
   * <code>optional int64 scheduledInterviewDateInMills = 5;</code>
   */
  public long getScheduledInterviewDateInMills() {
    return scheduledInterviewDateInMills_;
  }

  public static final int ISFINALFRAGMENT_FIELD_NUMBER = 6;
  private boolean isFinalFragment_;
  /**
   * <code>optional bool isFinalFragment = 6;</code>
   */
  public boolean getIsFinalFragment() {
    return isFinalFragment_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCandidateMobileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, candidateMobile_);
    }
    if (timeSlotId_ != 0) {
      output.writeInt32(2, timeSlotId_);
    }
    if (jobPostId_ != 0L) {
      output.writeInt64(4, jobPostId_);
    }
    if (scheduledInterviewDateInMills_ != 0L) {
      output.writeInt64(5, scheduledInterviewDateInMills_);
    }
    if (isFinalFragment_ != false) {
      output.writeBool(6, isFinalFragment_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCandidateMobileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, candidateMobile_);
    }
    if (timeSlotId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeSlotId_);
    }
    if (jobPostId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, jobPostId_);
    }
    if (scheduledInterviewDateInMills_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, scheduledInterviewDateInMills_);
    }
    if (isFinalFragment_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isFinalFragment_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.UpdateCandidateInterviewDetailRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.UpdateCandidateInterviewDetailRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.UpdateCandidateInterviewDetailRequest)
      in.trujobs.proto.UpdateCandidateInterviewDetailRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateInterviewDetailRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateInterviewDetailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.UpdateCandidateInterviewDetailRequest.class, in.trujobs.proto.UpdateCandidateInterviewDetailRequest.Builder.class);
    }

    // Construct using in.trujobs.proto.UpdateCandidateInterviewDetailRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      candidateMobile_ = "";

      timeSlotId_ = 0;

      jobPostId_ = 0L;

      scheduledInterviewDateInMills_ = 0L;

      isFinalFragment_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateInterviewDetailRequest_descriptor;
    }

    public in.trujobs.proto.UpdateCandidateInterviewDetailRequest getDefaultInstanceForType() {
      return in.trujobs.proto.UpdateCandidateInterviewDetailRequest.getDefaultInstance();
    }

    public in.trujobs.proto.UpdateCandidateInterviewDetailRequest build() {
      in.trujobs.proto.UpdateCandidateInterviewDetailRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.UpdateCandidateInterviewDetailRequest buildPartial() {
      in.trujobs.proto.UpdateCandidateInterviewDetailRequest result = new in.trujobs.proto.UpdateCandidateInterviewDetailRequest(this);
      result.candidateMobile_ = candidateMobile_;
      result.timeSlotId_ = timeSlotId_;
      result.jobPostId_ = jobPostId_;
      result.scheduledInterviewDateInMills_ = scheduledInterviewDateInMills_;
      result.isFinalFragment_ = isFinalFragment_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.UpdateCandidateInterviewDetailRequest) {
        return mergeFrom((in.trujobs.proto.UpdateCandidateInterviewDetailRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.UpdateCandidateInterviewDetailRequest other) {
      if (other == in.trujobs.proto.UpdateCandidateInterviewDetailRequest.getDefaultInstance()) return this;
      if (!other.getCandidateMobile().isEmpty()) {
        candidateMobile_ = other.candidateMobile_;
        onChanged();
      }
      if (other.getTimeSlotId() != 0) {
        setTimeSlotId(other.getTimeSlotId());
      }
      if (other.getJobPostId() != 0L) {
        setJobPostId(other.getJobPostId());
      }
      if (other.getScheduledInterviewDateInMills() != 0L) {
        setScheduledInterviewDateInMills(other.getScheduledInterviewDateInMills());
      }
      if (other.getIsFinalFragment() != false) {
        setIsFinalFragment(other.getIsFinalFragment());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.UpdateCandidateInterviewDetailRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.UpdateCandidateInterviewDetailRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object candidateMobile_ = "";
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public java.lang.String getCandidateMobile() {
      java.lang.Object ref = candidateMobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateMobile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateMobileBytes() {
      java.lang.Object ref = candidateMobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public Builder setCandidateMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      candidateMobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public Builder clearCandidateMobile() {
      
      candidateMobile_ = getDefaultInstance().getCandidateMobile();
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public Builder setCandidateMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      candidateMobile_ = value;
      onChanged();
      return this;
    }

    private int timeSlotId_ ;
    /**
     * <code>optional int32 timeSlotId = 2;</code>
     */
    public int getTimeSlotId() {
      return timeSlotId_;
    }
    /**
     * <code>optional int32 timeSlotId = 2;</code>
     */
    public Builder setTimeSlotId(int value) {
      
      timeSlotId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 timeSlotId = 2;</code>
     */
    public Builder clearTimeSlotId() {
      
      timeSlotId_ = 0;
      onChanged();
      return this;
    }

    private long jobPostId_ ;
    /**
     * <code>optional int64 jobPostId = 4;</code>
     */
    public long getJobPostId() {
      return jobPostId_;
    }
    /**
     * <code>optional int64 jobPostId = 4;</code>
     */
    public Builder setJobPostId(long value) {
      
      jobPostId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 jobPostId = 4;</code>
     */
    public Builder clearJobPostId() {
      
      jobPostId_ = 0L;
      onChanged();
      return this;
    }

    private long scheduledInterviewDateInMills_ ;
    /**
     * <code>optional int64 scheduledInterviewDateInMills = 5;</code>
     */
    public long getScheduledInterviewDateInMills() {
      return scheduledInterviewDateInMills_;
    }
    /**
     * <code>optional int64 scheduledInterviewDateInMills = 5;</code>
     */
    public Builder setScheduledInterviewDateInMills(long value) {
      
      scheduledInterviewDateInMills_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 scheduledInterviewDateInMills = 5;</code>
     */
    public Builder clearScheduledInterviewDateInMills() {
      
      scheduledInterviewDateInMills_ = 0L;
      onChanged();
      return this;
    }

    private boolean isFinalFragment_ ;
    /**
     * <code>optional bool isFinalFragment = 6;</code>
     */
    public boolean getIsFinalFragment() {
      return isFinalFragment_;
    }
    /**
     * <code>optional bool isFinalFragment = 6;</code>
     */
    public Builder setIsFinalFragment(boolean value) {
      
      isFinalFragment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isFinalFragment = 6;</code>
     */
    public Builder clearIsFinalFragment() {
      
      isFinalFragment_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.UpdateCandidateInterviewDetailRequest)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.UpdateCandidateInterviewDetailRequest)
  private static final in.trujobs.proto.UpdateCandidateInterviewDetailRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.UpdateCandidateInterviewDetailRequest();
  }

  public static in.trujobs.proto.UpdateCandidateInterviewDetailRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateCandidateInterviewDetailRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateCandidateInterviewDetailRequest>() {
    public UpdateCandidateInterviewDetailRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new UpdateCandidateInterviewDetailRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<UpdateCandidateInterviewDetailRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateCandidateInterviewDetailRequest> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.UpdateCandidateInterviewDetailRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

