// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface UpdateInterviewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.UpdateInterviewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  java.lang.String getCandidateMobile();
  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  com.google.protobuf.ByteString
      getCandidateMobileBytes();

  /**
   * <code>optional int64 jpId = 2;</code>
   */
  long getJpId();

  /**
   * <code>optional int32 interviewStatus = 3;</code>
   */
  int getInterviewStatus();
}
