// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

public interface UpdateCandidateExperienceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:in.trujobs.proto.UpdateCandidateExperienceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  java.lang.String getCandidateMobile();
  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  com.google.protobuf.ByteString
      getCandidateMobileBytes();

  /**
   * <code>optional int32 candidate_total_experience = 2;</code>
   */
  int getCandidateTotalExperience();

  /**
   * <code>optional int32 candidate_is_employed = 3;</code>
   */
  int getCandidateIsEmployed();

  /**
   * <code>optional string candidate_current_company = 4;</code>
   */
  java.lang.String getCandidateCurrentCompany();
  /**
   * <code>optional string candidate_current_company = 4;</code>
   */
  com.google.protobuf.ByteString
      getCandidateCurrentCompanyBytes();

  /**
   * <code>optional int64 candidate_current_salary = 5;</code>
   */
  long getCandidateCurrentSalary();

  /**
   * <code>optional .in.trujobs.proto.JobRoleObject current_job_role = 6;</code>
   */
  boolean hasCurrentJobRole();
  /**
   * <code>optional .in.trujobs.proto.JobRoleObject current_job_role = 6;</code>
   */
  in.trujobs.proto.JobRoleObject getCurrentJobRole();
  /**
   * <code>optional .in.trujobs.proto.JobRoleObject current_job_role = 6;</code>
   */
  in.trujobs.proto.JobRoleObjectOrBuilder getCurrentJobRoleOrBuilder();

  /**
   * <code>optional int64 jobPostId = 7;</code>
   */
  long getJobPostId();

  /**
   * <code>optional bool isFinalFragment = 8;</code>
   */
  boolean getIsFinalFragment();
}
