// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen.proto

package in.trujobs.proto;

/**
 * Protobuf type {@code in.trujobs.proto.UpdateCandidateOtherRequest}
 */
public  final class UpdateCandidateOtherRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:in.trujobs.proto.UpdateCandidateOtherRequest)
    UpdateCandidateOtherRequestOrBuilder {
  // Use UpdateCandidateOtherRequest.newBuilder() to construct.
  private UpdateCandidateOtherRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateCandidateOtherRequest() {
    candidateMobile_ = "";
    propertyId_ = java.util.Collections.emptyList();
    candidateDOB_ = "";
    candidateLastWithdrawnSalary_ = 0L;
    candidateTimeshiftPref_ = 0L;
    candidateGender_ = 0;
    assetId_ = java.util.Collections.emptyList();
    jobPostId_ = 0L;
    isFinalFragment_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateCandidateOtherRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            candidateMobile_ = s;
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              propertyId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            propertyId_.add(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              propertyId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              propertyId_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            candidateDOB_ = s;
            break;
          }
          case 32: {

            candidateLastWithdrawnSalary_ = input.readInt64();
            break;
          }
          case 40: {

            candidateTimeshiftPref_ = input.readInt64();
            break;
          }
          case 48: {

            candidateGender_ = input.readInt32();
            break;
          }
          case 56: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              assetId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000040;
            }
            assetId_.add(input.readInt32());
            break;
          }
          case 58: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
              assetId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000040;
            }
            while (input.getBytesUntilLimit() > 0) {
              assetId_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 64: {

            jobPostId_ = input.readInt64();
            break;
          }
          case 72: {

            isFinalFragment_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        propertyId_ = java.util.Collections.unmodifiableList(propertyId_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        assetId_ = java.util.Collections.unmodifiableList(assetId_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateOtherRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateOtherRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.trujobs.proto.UpdateCandidateOtherRequest.class, in.trujobs.proto.UpdateCandidateOtherRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CANDIDATE_MOBILE_FIELD_NUMBER = 1;
  private volatile java.lang.Object candidateMobile_;
  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  public java.lang.String getCandidateMobile() {
    java.lang.Object ref = candidateMobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateMobile_ = s;
      return s;
    }
  }
  /**
   * <code>optional string candidate_mobile = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCandidateMobileBytes() {
    java.lang.Object ref = candidateMobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateMobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROPERTYID_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> propertyId_;
  /**
   * <code>repeated int32 propertyId = 2 [packed = true];</code>
   */
  public java.util.List<java.lang.Integer>
      getPropertyIdList() {
    return propertyId_;
  }
  /**
   * <code>repeated int32 propertyId = 2 [packed = true];</code>
   */
  public int getPropertyIdCount() {
    return propertyId_.size();
  }
  /**
   * <code>repeated int32 propertyId = 2 [packed = true];</code>
   */
  public int getPropertyId(int index) {
    return propertyId_.get(index);
  }
  private int propertyIdMemoizedSerializedSize = -1;

  public static final int CANDIDATEDOB_FIELD_NUMBER = 3;
  private volatile java.lang.Object candidateDOB_;
  /**
   * <code>optional string candidateDOB = 3;</code>
   */
  public java.lang.String getCandidateDOB() {
    java.lang.Object ref = candidateDOB_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateDOB_ = s;
      return s;
    }
  }
  /**
   * <code>optional string candidateDOB = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCandidateDOBBytes() {
    java.lang.Object ref = candidateDOB_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateDOB_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATELASTWITHDRAWNSALARY_FIELD_NUMBER = 4;
  private long candidateLastWithdrawnSalary_;
  /**
   * <code>optional int64 candidateLastWithdrawnSalary = 4;</code>
   */
  public long getCandidateLastWithdrawnSalary() {
    return candidateLastWithdrawnSalary_;
  }

  public static final int CANDIDATE_TIMESHIFT_PREF_FIELD_NUMBER = 5;
  private long candidateTimeshiftPref_;
  /**
   * <code>optional int64 candidate_timeshift_pref = 5;</code>
   */
  public long getCandidateTimeshiftPref() {
    return candidateTimeshiftPref_;
  }

  public static final int CANDIDATEGENDER_FIELD_NUMBER = 6;
  private int candidateGender_;
  /**
   * <code>optional int32 candidateGender = 6;</code>
   */
  public int getCandidateGender() {
    return candidateGender_;
  }

  public static final int ASSETID_FIELD_NUMBER = 7;
  private java.util.List<java.lang.Integer> assetId_;
  /**
   * <code>repeated int32 assetId = 7;</code>
   */
  public java.util.List<java.lang.Integer>
      getAssetIdList() {
    return assetId_;
  }
  /**
   * <code>repeated int32 assetId = 7;</code>
   */
  public int getAssetIdCount() {
    return assetId_.size();
  }
  /**
   * <code>repeated int32 assetId = 7;</code>
   */
  public int getAssetId(int index) {
    return assetId_.get(index);
  }
  private int assetIdMemoizedSerializedSize = -1;

  public static final int JOBPOSTID_FIELD_NUMBER = 8;
  private long jobPostId_;
  /**
   * <code>optional int64 jobPostId = 8;</code>
   */
  public long getJobPostId() {
    return jobPostId_;
  }

  public static final int ISFINALFRAGMENT_FIELD_NUMBER = 9;
  private boolean isFinalFragment_;
  /**
   * <code>optional bool isFinalFragment = 9;</code>
   */
  public boolean getIsFinalFragment() {
    return isFinalFragment_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getCandidateMobileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, candidateMobile_);
    }
    if (getPropertyIdList().size() > 0) {
      output.writeRawVarint32(18);
      output.writeRawVarint32(propertyIdMemoizedSerializedSize);
    }
    for (int i = 0; i < propertyId_.size(); i++) {
      output.writeInt32NoTag(propertyId_.get(i));
    }
    if (!getCandidateDOBBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, candidateDOB_);
    }
    if (candidateLastWithdrawnSalary_ != 0L) {
      output.writeInt64(4, candidateLastWithdrawnSalary_);
    }
    if (candidateTimeshiftPref_ != 0L) {
      output.writeInt64(5, candidateTimeshiftPref_);
    }
    if (candidateGender_ != 0) {
      output.writeInt32(6, candidateGender_);
    }
    if (getAssetIdList().size() > 0) {
      output.writeRawVarint32(58);
      output.writeRawVarint32(assetIdMemoizedSerializedSize);
    }
    for (int i = 0; i < assetId_.size(); i++) {
      output.writeInt32NoTag(assetId_.get(i));
    }
    if (jobPostId_ != 0L) {
      output.writeInt64(8, jobPostId_);
    }
    if (isFinalFragment_ != false) {
      output.writeBool(9, isFinalFragment_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCandidateMobileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, candidateMobile_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < propertyId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(propertyId_.get(i));
      }
      size += dataSize;
      if (!getPropertyIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      propertyIdMemoizedSerializedSize = dataSize;
    }
    if (!getCandidateDOBBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, candidateDOB_);
    }
    if (candidateLastWithdrawnSalary_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, candidateLastWithdrawnSalary_);
    }
    if (candidateTimeshiftPref_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, candidateTimeshiftPref_);
    }
    if (candidateGender_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, candidateGender_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < assetId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(assetId_.get(i));
      }
      size += dataSize;
      if (!getAssetIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      assetIdMemoizedSerializedSize = dataSize;
    }
    if (jobPostId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, jobPostId_);
    }
    if (isFinalFragment_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isFinalFragment_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static in.trujobs.proto.UpdateCandidateOtherRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.trujobs.proto.UpdateCandidateOtherRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code in.trujobs.proto.UpdateCandidateOtherRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:in.trujobs.proto.UpdateCandidateOtherRequest)
      in.trujobs.proto.UpdateCandidateOtherRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateOtherRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateOtherRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.trujobs.proto.UpdateCandidateOtherRequest.class, in.trujobs.proto.UpdateCandidateOtherRequest.Builder.class);
    }

    // Construct using in.trujobs.proto.UpdateCandidateOtherRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      candidateMobile_ = "";

      propertyId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      candidateDOB_ = "";

      candidateLastWithdrawnSalary_ = 0L;

      candidateTimeshiftPref_ = 0L;

      candidateGender_ = 0;

      assetId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);
      jobPostId_ = 0L;

      isFinalFragment_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.trujobs.proto.Gen.internal_static_in_trujobs_proto_UpdateCandidateOtherRequest_descriptor;
    }

    public in.trujobs.proto.UpdateCandidateOtherRequest getDefaultInstanceForType() {
      return in.trujobs.proto.UpdateCandidateOtherRequest.getDefaultInstance();
    }

    public in.trujobs.proto.UpdateCandidateOtherRequest build() {
      in.trujobs.proto.UpdateCandidateOtherRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public in.trujobs.proto.UpdateCandidateOtherRequest buildPartial() {
      in.trujobs.proto.UpdateCandidateOtherRequest result = new in.trujobs.proto.UpdateCandidateOtherRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.candidateMobile_ = candidateMobile_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        propertyId_ = java.util.Collections.unmodifiableList(propertyId_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.propertyId_ = propertyId_;
      result.candidateDOB_ = candidateDOB_;
      result.candidateLastWithdrawnSalary_ = candidateLastWithdrawnSalary_;
      result.candidateTimeshiftPref_ = candidateTimeshiftPref_;
      result.candidateGender_ = candidateGender_;
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        assetId_ = java.util.Collections.unmodifiableList(assetId_);
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.assetId_ = assetId_;
      result.jobPostId_ = jobPostId_;
      result.isFinalFragment_ = isFinalFragment_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.trujobs.proto.UpdateCandidateOtherRequest) {
        return mergeFrom((in.trujobs.proto.UpdateCandidateOtherRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.trujobs.proto.UpdateCandidateOtherRequest other) {
      if (other == in.trujobs.proto.UpdateCandidateOtherRequest.getDefaultInstance()) return this;
      if (!other.getCandidateMobile().isEmpty()) {
        candidateMobile_ = other.candidateMobile_;
        onChanged();
      }
      if (!other.propertyId_.isEmpty()) {
        if (propertyId_.isEmpty()) {
          propertyId_ = other.propertyId_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensurePropertyIdIsMutable();
          propertyId_.addAll(other.propertyId_);
        }
        onChanged();
      }
      if (!other.getCandidateDOB().isEmpty()) {
        candidateDOB_ = other.candidateDOB_;
        onChanged();
      }
      if (other.getCandidateLastWithdrawnSalary() != 0L) {
        setCandidateLastWithdrawnSalary(other.getCandidateLastWithdrawnSalary());
      }
      if (other.getCandidateTimeshiftPref() != 0L) {
        setCandidateTimeshiftPref(other.getCandidateTimeshiftPref());
      }
      if (other.getCandidateGender() != 0) {
        setCandidateGender(other.getCandidateGender());
      }
      if (!other.assetId_.isEmpty()) {
        if (assetId_.isEmpty()) {
          assetId_ = other.assetId_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureAssetIdIsMutable();
          assetId_.addAll(other.assetId_);
        }
        onChanged();
      }
      if (other.getJobPostId() != 0L) {
        setJobPostId(other.getJobPostId());
      }
      if (other.getIsFinalFragment() != false) {
        setIsFinalFragment(other.getIsFinalFragment());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.trujobs.proto.UpdateCandidateOtherRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.trujobs.proto.UpdateCandidateOtherRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object candidateMobile_ = "";
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public java.lang.String getCandidateMobile() {
      java.lang.Object ref = candidateMobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateMobile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateMobileBytes() {
      java.lang.Object ref = candidateMobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public Builder setCandidateMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      candidateMobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public Builder clearCandidateMobile() {
      
      candidateMobile_ = getDefaultInstance().getCandidateMobile();
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidate_mobile = 1;</code>
     */
    public Builder setCandidateMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      candidateMobile_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> propertyId_ = java.util.Collections.emptyList();
    private void ensurePropertyIdIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        propertyId_ = new java.util.ArrayList<java.lang.Integer>(propertyId_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getPropertyIdList() {
      return java.util.Collections.unmodifiableList(propertyId_);
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public int getPropertyIdCount() {
      return propertyId_.size();
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public int getPropertyId(int index) {
      return propertyId_.get(index);
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public Builder setPropertyId(
        int index, int value) {
      ensurePropertyIdIsMutable();
      propertyId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public Builder addPropertyId(int value) {
      ensurePropertyIdIsMutable();
      propertyId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public Builder addAllPropertyId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePropertyIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, propertyId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 propertyId = 2 [packed = true];</code>
     */
    public Builder clearPropertyId() {
      propertyId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.lang.Object candidateDOB_ = "";
    /**
     * <code>optional string candidateDOB = 3;</code>
     */
    public java.lang.String getCandidateDOB() {
      java.lang.Object ref = candidateDOB_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateDOB_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string candidateDOB = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateDOBBytes() {
      java.lang.Object ref = candidateDOB_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateDOB_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string candidateDOB = 3;</code>
     */
    public Builder setCandidateDOB(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      candidateDOB_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidateDOB = 3;</code>
     */
    public Builder clearCandidateDOB() {
      
      candidateDOB_ = getDefaultInstance().getCandidateDOB();
      onChanged();
      return this;
    }
    /**
     * <code>optional string candidateDOB = 3;</code>
     */
    public Builder setCandidateDOBBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      candidateDOB_ = value;
      onChanged();
      return this;
    }

    private long candidateLastWithdrawnSalary_ ;
    /**
     * <code>optional int64 candidateLastWithdrawnSalary = 4;</code>
     */
    public long getCandidateLastWithdrawnSalary() {
      return candidateLastWithdrawnSalary_;
    }
    /**
     * <code>optional int64 candidateLastWithdrawnSalary = 4;</code>
     */
    public Builder setCandidateLastWithdrawnSalary(long value) {
      
      candidateLastWithdrawnSalary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 candidateLastWithdrawnSalary = 4;</code>
     */
    public Builder clearCandidateLastWithdrawnSalary() {
      
      candidateLastWithdrawnSalary_ = 0L;
      onChanged();
      return this;
    }

    private long candidateTimeshiftPref_ ;
    /**
     * <code>optional int64 candidate_timeshift_pref = 5;</code>
     */
    public long getCandidateTimeshiftPref() {
      return candidateTimeshiftPref_;
    }
    /**
     * <code>optional int64 candidate_timeshift_pref = 5;</code>
     */
    public Builder setCandidateTimeshiftPref(long value) {
      
      candidateTimeshiftPref_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 candidate_timeshift_pref = 5;</code>
     */
    public Builder clearCandidateTimeshiftPref() {
      
      candidateTimeshiftPref_ = 0L;
      onChanged();
      return this;
    }

    private int candidateGender_ ;
    /**
     * <code>optional int32 candidateGender = 6;</code>
     */
    public int getCandidateGender() {
      return candidateGender_;
    }
    /**
     * <code>optional int32 candidateGender = 6;</code>
     */
    public Builder setCandidateGender(int value) {
      
      candidateGender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 candidateGender = 6;</code>
     */
    public Builder clearCandidateGender() {
      
      candidateGender_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> assetId_ = java.util.Collections.emptyList();
    private void ensureAssetIdIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        assetId_ = new java.util.ArrayList<java.lang.Integer>(assetId_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public java.util.List<java.lang.Integer>
        getAssetIdList() {
      return java.util.Collections.unmodifiableList(assetId_);
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public int getAssetIdCount() {
      return assetId_.size();
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public int getAssetId(int index) {
      return assetId_.get(index);
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public Builder setAssetId(
        int index, int value) {
      ensureAssetIdIsMutable();
      assetId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public Builder addAssetId(int value) {
      ensureAssetIdIsMutable();
      assetId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public Builder addAllAssetId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureAssetIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, assetId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 assetId = 7;</code>
     */
    public Builder clearAssetId() {
      assetId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }

    private long jobPostId_ ;
    /**
     * <code>optional int64 jobPostId = 8;</code>
     */
    public long getJobPostId() {
      return jobPostId_;
    }
    /**
     * <code>optional int64 jobPostId = 8;</code>
     */
    public Builder setJobPostId(long value) {
      
      jobPostId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 jobPostId = 8;</code>
     */
    public Builder clearJobPostId() {
      
      jobPostId_ = 0L;
      onChanged();
      return this;
    }

    private boolean isFinalFragment_ ;
    /**
     * <code>optional bool isFinalFragment = 9;</code>
     */
    public boolean getIsFinalFragment() {
      return isFinalFragment_;
    }
    /**
     * <code>optional bool isFinalFragment = 9;</code>
     */
    public Builder setIsFinalFragment(boolean value) {
      
      isFinalFragment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isFinalFragment = 9;</code>
     */
    public Builder clearIsFinalFragment() {
      
      isFinalFragment_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:in.trujobs.proto.UpdateCandidateOtherRequest)
  }

  // @@protoc_insertion_point(class_scope:in.trujobs.proto.UpdateCandidateOtherRequest)
  private static final in.trujobs.proto.UpdateCandidateOtherRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.trujobs.proto.UpdateCandidateOtherRequest();
  }

  public static in.trujobs.proto.UpdateCandidateOtherRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateCandidateOtherRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateCandidateOtherRequest>() {
    public UpdateCandidateOtherRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new UpdateCandidateOtherRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<UpdateCandidateOtherRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateCandidateOtherRequest> getParserForType() {
    return PARSER;
  }

  public in.trujobs.proto.UpdateCandidateOtherRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

